source 'https://rubygems.org/'

gem 'redis', '~>3.3.0'
gem 'rest-client'
gem 'term-ansicolor'


group :test do
  gem 'mocha'
  # single test runner
  gem 'm'
  gem 'dotenv'
  gem 'minitest', '~>5.10.3'
  gem 'minitest-reporters'
  gem 'rake'
  gem 'simplecov', :require => false
end
