source 'https://rubygems.org/'

gem 'rake', '~>12.3'
gem 'redis', '~>3.3.0'
gem 'rest-client'
gem 'term-ansicolor'
gem 'parallel'

group :test do
  gem 'mocha'
  # single test runner
  gem 'm'
  gem 'dotenv'
  gem 'minitest', '~>5.10.3'
  gem 'minitest-reporters'
  gem 'simplecov', :require => false
end
