# encoding: utf-8

require 'test_helper'

module Nls

  module EndpointInterpret

    class TestEntities < NlsTestCommon

      def setup
        super

        Nls.remove_all_packages

        Interpretation.default_locale = "en"

        Nls.package_update(create_package)
      end

      def create_package
        package = Package.new("test_entities")

        # we create 500 entities (and a few more) as it is the limit for entities to be created
        car = package.new_interpretation("entities", { scope: "public" })

        car << Expression.new("maison de campagne", solution: "maison de campagne", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("chemin du petit", solution: "chemin du petit", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("chemin du petit bois", solution: "chemin du petit bois", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("rivière de la belle etoile", solution: "rivière de la belle etoile", keep_order: true, glued: true, glue_strength: "punctuation")


        car << Expression.new("aaa aaa aaa", solution: "aaa aaa aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa aaa bbb", solution: "aaa aaa bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa aaa ccc", solution: "aaa aaa ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa aaa ddd", solution: "aaa aaa ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa aaa eee", solution: "aaa aaa eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa aaa fff", solution: "aaa aaa fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa aaa ggg", solution: "aaa aaa ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa aaa hhh", solution: "aaa aaa hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa aaa iii", solution: "aaa aaa iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa aaa jjj", solution: "aaa aaa jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa bbb aaa", solution: "aaa bbb aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa bbb bbb", solution: "aaa bbb bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa bbb ccc", solution: "aaa bbb ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa bbb ddd", solution: "aaa bbb ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa bbb eee", solution: "aaa bbb eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa bbb fff", solution: "aaa bbb fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa bbb ggg", solution: "aaa bbb ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa bbb hhh", solution: "aaa bbb hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa bbb iii", solution: "aaa bbb iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa bbb jjj", solution: "aaa bbb jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa ccc aaa", solution: "aaa ccc aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa ccc bbb", solution: "aaa ccc bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa ccc ccc", solution: "aaa ccc ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa ccc ddd", solution: "aaa ccc ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa ccc eee", solution: "aaa ccc eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa ccc fff", solution: "aaa ccc fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa ccc ggg", solution: "aaa ccc ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa ccc hhh", solution: "aaa ccc hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa ccc iii", solution: "aaa ccc iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa ccc jjj", solution: "aaa ccc jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa ddd aaa", solution: "aaa ddd aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa ddd bbb", solution: "aaa ddd bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa ddd ccc", solution: "aaa ddd ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa ddd ddd", solution: "aaa ddd ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa ddd eee", solution: "aaa ddd eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa ddd fff", solution: "aaa ddd fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa ddd ggg", solution: "aaa ddd ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa ddd hhh", solution: "aaa ddd hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa ddd iii", solution: "aaa ddd iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa ddd jjj", solution: "aaa ddd jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa eee aaa", solution: "aaa eee aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa eee bbb", solution: "aaa eee bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa eee ccc", solution: "aaa eee ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa eee ddd", solution: "aaa eee ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa eee eee", solution: "aaa eee eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa eee fff", solution: "aaa eee fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa eee ggg", solution: "aaa eee ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa eee hhh", solution: "aaa eee hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa eee iii", solution: "aaa eee iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa eee jjj", solution: "aaa eee jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa fff aaa", solution: "aaa fff aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa fff bbb", solution: "aaa fff bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa fff ccc", solution: "aaa fff ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa fff ddd", solution: "aaa fff ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa fff eee", solution: "aaa fff eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa fff fff", solution: "aaa fff fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa fff ggg", solution: "aaa fff ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa fff hhh", solution: "aaa fff hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa fff iii", solution: "aaa fff iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa fff jjj", solution: "aaa fff jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa ggg aaa", solution: "aaa ggg aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa ggg bbb", solution: "aaa ggg bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa ggg ccc", solution: "aaa ggg ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa ggg ddd", solution: "aaa ggg ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa ggg eee", solution: "aaa ggg eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa ggg fff", solution: "aaa ggg fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa ggg ggg", solution: "aaa ggg ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa ggg hhh", solution: "aaa ggg hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa ggg iii", solution: "aaa ggg iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa ggg jjj", solution: "aaa ggg jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa hhh aaa", solution: "aaa hhh aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa hhh bbb", solution: "aaa hhh bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa hhh ccc", solution: "aaa hhh ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa hhh ddd", solution: "aaa hhh ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa hhh eee", solution: "aaa hhh eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa hhh fff", solution: "aaa hhh fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa hhh ggg", solution: "aaa hhh ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa hhh hhh", solution: "aaa hhh hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa hhh iii", solution: "aaa hhh iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa hhh jjj", solution: "aaa hhh jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa iii aaa", solution: "aaa iii aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa iii bbb", solution: "aaa iii bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa iii ccc", solution: "aaa iii ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa iii ddd", solution: "aaa iii ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa iii eee", solution: "aaa iii eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa iii fff", solution: "aaa iii fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa iii ggg", solution: "aaa iii ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa iii hhh", solution: "aaa iii hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa iii iii", solution: "aaa iii iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa iii jjj", solution: "aaa iii jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa jjj aaa", solution: "aaa jjj aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa jjj bbb", solution: "aaa jjj bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa jjj ccc", solution: "aaa jjj ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa jjj ddd", solution: "aaa jjj ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa jjj eee", solution: "aaa jjj eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa jjj fff", solution: "aaa jjj fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa jjj ggg", solution: "aaa jjj ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa jjj hhh", solution: "aaa jjj hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa jjj iii", solution: "aaa jjj iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("aaa jjj jjj", solution: "aaa jjj jjj", keep_order: true, glued: true, glue_strength: "punctuation")

        car << Expression.new("bbb aaa aaa", solution: "bbb aaa aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb aaa bbb", solution: "bbb aaa bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb aaa ccc", solution: "bbb aaa ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb aaa ddd", solution: "bbb aaa ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb aaa eee", solution: "bbb aaa eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb aaa fff", solution: "bbb aaa fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb aaa ggg", solution: "bbb aaa ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb aaa hhh", solution: "bbb aaa hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb aaa iii", solution: "bbb aaa iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb aaa jjj", solution: "bbb aaa jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb bbb aaa", solution: "bbb bbb aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb bbb bbb", solution: "bbb bbb bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb bbb ccc", solution: "bbb bbb ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb bbb ddd", solution: "bbb bbb ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb bbb eee", solution: "bbb bbb eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb bbb fff", solution: "bbb bbb fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb bbb ggg", solution: "bbb bbb ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb bbb hhh", solution: "bbb bbb hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb bbb iii", solution: "bbb bbb iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb bbb jjj", solution: "bbb bbb jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb ccc aaa", solution: "bbb ccc aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb ccc bbb", solution: "bbb ccc bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb ccc ccc", solution: "bbb ccc ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb ccc ddd", solution: "bbb ccc ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb ccc eee", solution: "bbb ccc eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb ccc fff", solution: "bbb ccc fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb ccc ggg", solution: "bbb ccc ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb ccc hhh", solution: "bbb ccc hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb ccc iii", solution: "bbb ccc iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb ccc jjj", solution: "bbb ccc jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb ddd aaa", solution: "bbb ddd aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb ddd bbb", solution: "bbb ddd bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb ddd ccc", solution: "bbb ddd ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb ddd ddd", solution: "bbb ddd ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb ddd eee", solution: "bbb ddd eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb ddd fff", solution: "bbb ddd fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb ddd ggg", solution: "bbb ddd ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb ddd hhh", solution: "bbb ddd hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb ddd iii", solution: "bbb ddd iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb ddd jjj", solution: "bbb ddd jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb eee aaa", solution: "bbb eee aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb eee bbb", solution: "bbb eee bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb eee ccc", solution: "bbb eee ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb eee ddd", solution: "bbb eee ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb eee eee", solution: "bbb eee eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb eee fff", solution: "bbb eee fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb eee ggg", solution: "bbb eee ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb eee hhh", solution: "bbb eee hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb eee iii", solution: "bbb eee iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb eee jjj", solution: "bbb eee jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb fff aaa", solution: "bbb fff aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb fff bbb", solution: "bbb fff bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb fff ccc", solution: "bbb fff ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb fff ddd", solution: "bbb fff ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb fff eee", solution: "bbb fff eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb fff fff", solution: "bbb fff fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb fff ggg", solution: "bbb fff ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb fff hhh", solution: "bbb fff hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb fff iii", solution: "bbb fff iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb fff jjj", solution: "bbb fff jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb ggg aaa", solution: "bbb ggg aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb ggg bbb", solution: "bbb ggg bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb ggg ccc", solution: "bbb ggg ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb ggg ddd", solution: "bbb ggg ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb ggg eee", solution: "bbb ggg eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb ggg fff", solution: "bbb ggg fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb ggg ggg", solution: "bbb ggg ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb ggg hhh", solution: "bbb ggg hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb ggg iii", solution: "bbb ggg iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb ggg jjj", solution: "bbb ggg jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb hhh aaa", solution: "bbb hhh aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb hhh bbb", solution: "bbb hhh bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb hhh ccc", solution: "bbb hhh ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb hhh ddd", solution: "bbb hhh ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb hhh eee", solution: "bbb hhh eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb hhh fff", solution: "bbb hhh fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb hhh ggg", solution: "bbb hhh ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb hhh hhh", solution: "bbb hhh hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb hhh iii", solution: "bbb hhh iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb hhh jjj", solution: "bbb hhh jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb iii aaa", solution: "bbb iii aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb iii bbb", solution: "bbb iii bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb iii ccc", solution: "bbb iii ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb iii ddd", solution: "bbb iii ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb iii eee", solution: "bbb iii eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb iii fff", solution: "bbb iii fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb iii ggg", solution: "bbb iii ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb iii hhh", solution: "bbb iii hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb iii iii", solution: "bbb iii iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb iii jjj", solution: "bbb iii jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb jjj aaa", solution: "bbb jjj aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb jjj bbb", solution: "bbb jjj bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb jjj ccc", solution: "bbb jjj ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb jjj ddd", solution: "bbb jjj ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb jjj eee", solution: "bbb jjj eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb jjj fff", solution: "bbb jjj fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb jjj ggg", solution: "bbb jjj ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb jjj hhh", solution: "bbb jjj hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb jjj iii", solution: "bbb jjj iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("bbb jjj jjj", solution: "bbb jjj jjj", keep_order: true, glued: true, glue_strength: "punctuation")


        car << Expression.new("ccc aaa aaa", solution: "ccc aaa aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc aaa bbb", solution: "ccc aaa bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc aaa ccc", solution: "ccc aaa ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc aaa ddd", solution: "ccc aaa ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc aaa eee", solution: "ccc aaa eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc aaa fff", solution: "ccc aaa fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc aaa ggg", solution: "ccc aaa ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc aaa hhh", solution: "ccc aaa hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc aaa iii", solution: "ccc aaa iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc aaa jjj", solution: "ccc aaa jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc bbb aaa", solution: "ccc bbb aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc bbb bbb", solution: "ccc bbb bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc bbb ccc", solution: "ccc bbb ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc bbb ddd", solution: "ccc bbb ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc bbb eee", solution: "ccc bbb eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc bbb fff", solution: "ccc bbb fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc bbb ggg", solution: "ccc bbb ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc bbb hhh", solution: "ccc bbb hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc bbb iii", solution: "ccc bbb iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc bbb jjj", solution: "ccc bbb jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc ccc aaa", solution: "ccc ccc aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc ccc bbb", solution: "ccc ccc bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc ccc ccc", solution: "ccc ccc ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc ccc ddd", solution: "ccc ccc ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc ccc eee", solution: "ccc ccc eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc ccc fff", solution: "ccc ccc fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc ccc ggg", solution: "ccc ccc ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc ccc hhh", solution: "ccc ccc hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc ccc iii", solution: "ccc ccc iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc ccc jjj", solution: "ccc ccc jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc ddd aaa", solution: "ccc ddd aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc ddd bbb", solution: "ccc ddd bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc ddd ccc", solution: "ccc ddd ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc ddd ddd", solution: "ccc ddd ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc ddd eee", solution: "ccc ddd eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc ddd fff", solution: "ccc ddd fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc ddd ggg", solution: "ccc ddd ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc ddd hhh", solution: "ccc ddd hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc ddd iii", solution: "ccc ddd iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc ddd jjj", solution: "ccc ddd jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc eee aaa", solution: "ccc eee aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc eee bbb", solution: "ccc eee bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc eee ccc", solution: "ccc eee ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc eee ddd", solution: "ccc eee ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc eee eee", solution: "ccc eee eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc eee fff", solution: "ccc eee fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc eee ggg", solution: "ccc eee ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc eee hhh", solution: "ccc eee hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc eee iii", solution: "ccc eee iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc eee jjj", solution: "ccc eee jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc fff aaa", solution: "ccc fff aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc fff bbb", solution: "ccc fff bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc fff ccc", solution: "ccc fff ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc fff ddd", solution: "ccc fff ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc fff eee", solution: "ccc fff eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc fff fff", solution: "ccc fff fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc fff ggg", solution: "ccc fff ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc fff hhh", solution: "ccc fff hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc fff iii", solution: "ccc fff iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc fff jjj", solution: "ccc fff jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc ggg aaa", solution: "ccc ggg aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc ggg bbb", solution: "ccc ggg bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc ggg ccc", solution: "ccc ggg ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc ggg ddd", solution: "ccc ggg ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc ggg eee", solution: "ccc ggg eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc ggg fff", solution: "ccc ggg fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc ggg ggg", solution: "ccc ggg ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc ggg hhh", solution: "ccc ggg hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc ggg iii", solution: "ccc ggg iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc ggg jjj", solution: "ccc ggg jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc hhh aaa", solution: "ccc hhh aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc hhh bbb", solution: "ccc hhh bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc hhh ccc", solution: "ccc hhh ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc hhh ddd", solution: "ccc hhh ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc hhh eee", solution: "ccc hhh eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc hhh fff", solution: "ccc hhh fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc hhh ggg", solution: "ccc hhh ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc hhh hhh", solution: "ccc hhh hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc hhh iii", solution: "ccc hhh iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc hhh jjj", solution: "ccc hhh jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc iii aaa", solution: "ccc iii aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc iii bbb", solution: "ccc iii bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc iii ccc", solution: "ccc iii ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc iii ddd", solution: "ccc iii ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc iii eee", solution: "ccc iii eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc iii fff", solution: "ccc iii fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc iii ggg", solution: "ccc iii ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc iii hhh", solution: "ccc iii hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc iii iii", solution: "ccc iii iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc iii jjj", solution: "ccc iii jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc jjj aaa", solution: "ccc jjj aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc jjj bbb", solution: "ccc jjj bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc jjj ccc", solution: "ccc jjj ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc jjj ddd", solution: "ccc jjj ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc jjj eee", solution: "ccc jjj eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc jjj fff", solution: "ccc jjj fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc jjj ggg", solution: "ccc jjj ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc jjj hhh", solution: "ccc jjj hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc jjj iii", solution: "ccc jjj iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ccc jjj jjj", solution: "ccc jjj jjj", keep_order: true, glued: true, glue_strength: "punctuation")


        car << Expression.new("ddd aaa aaa", solution: "ddd aaa aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd aaa bbb", solution: "ddd aaa bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd aaa ccc", solution: "ddd aaa ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd aaa ddd", solution: "ddd aaa ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd aaa eee", solution: "ddd aaa eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd aaa fff", solution: "ddd aaa fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd aaa ggg", solution: "ddd aaa ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd aaa hhh", solution: "ddd aaa hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd aaa iii", solution: "ddd aaa iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd aaa jjj", solution: "ddd aaa jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd bbb aaa", solution: "ddd bbb aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd bbb bbb", solution: "ddd bbb bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd bbb ccc", solution: "ddd bbb ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd bbb ddd", solution: "ddd bbb ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd bbb eee", solution: "ddd bbb eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd bbb fff", solution: "ddd bbb fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd bbb ggg", solution: "ddd bbb ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd bbb hhh", solution: "ddd bbb hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd bbb iii", solution: "ddd bbb iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd bbb jjj", solution: "ddd bbb jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd ccc aaa", solution: "ddd ccc aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd ccc bbb", solution: "ddd ccc bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd ccc ccc", solution: "ddd ccc ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd ccc ddd", solution: "ddd ccc ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd ccc eee", solution: "ddd ccc eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd ccc fff", solution: "ddd ccc fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd ccc ggg", solution: "ddd ccc ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd ccc hhh", solution: "ddd ccc hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd ccc iii", solution: "ddd ccc iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd ccc jjj", solution: "ddd ccc jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd ddd aaa", solution: "ddd ddd aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd ddd bbb", solution: "ddd ddd bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd ddd ccc", solution: "ddd ddd ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd ddd ddd", solution: "ddd ddd ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd ddd eee", solution: "ddd ddd eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd ddd fff", solution: "ddd ddd fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd ddd ggg", solution: "ddd ddd ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd ddd hhh", solution: "ddd ddd hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd ddd iii", solution: "ddd ddd iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd ddd jjj", solution: "ddd ddd jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd eee aaa", solution: "ddd eee aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd eee bbb", solution: "ddd eee bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd eee ccc", solution: "ddd eee ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd eee ddd", solution: "ddd eee ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd eee eee", solution: "ddd eee eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd eee fff", solution: "ddd eee fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd eee ggg", solution: "ddd eee ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd eee hhh", solution: "ddd eee hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd eee iii", solution: "ddd eee iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd eee jjj", solution: "ddd eee jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd fff aaa", solution: "ddd fff aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd fff bbb", solution: "ddd fff bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd fff ccc", solution: "ddd fff ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd fff ddd", solution: "ddd fff ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd fff eee", solution: "ddd fff eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd fff fff", solution: "ddd fff fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd fff ggg", solution: "ddd fff ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd fff hhh", solution: "ddd fff hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd fff iii", solution: "ddd fff iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd fff jjj", solution: "ddd fff jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd ggg aaa", solution: "ddd ggg aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd ggg bbb", solution: "ddd ggg bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd ggg ccc", solution: "ddd ggg ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd ggg ddd", solution: "ddd ggg ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd ggg eee", solution: "ddd ggg eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd ggg fff", solution: "ddd ggg fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd ggg ggg", solution: "ddd ggg ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd ggg hhh", solution: "ddd ggg hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd ggg iii", solution: "ddd ggg iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd ggg jjj", solution: "ddd ggg jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd hhh aaa", solution: "ddd hhh aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd hhh bbb", solution: "ddd hhh bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd hhh ccc", solution: "ddd hhh ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd hhh ddd", solution: "ddd hhh ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd hhh eee", solution: "ddd hhh eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd hhh fff", solution: "ddd hhh fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd hhh ggg", solution: "ddd hhh ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd hhh hhh", solution: "ddd hhh hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd hhh iii", solution: "ddd hhh iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd hhh jjj", solution: "ddd hhh jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd iii aaa", solution: "ddd iii aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd iii bbb", solution: "ddd iii bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd iii ccc", solution: "ddd iii ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd iii ddd", solution: "ddd iii ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd iii eee", solution: "ddd iii eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd iii fff", solution: "ddd iii fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd iii ggg", solution: "ddd iii ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd iii hhh", solution: "ddd iii hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd iii iii", solution: "ddd iii iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd iii jjj", solution: "ddd iii jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd jjj aaa", solution: "ddd jjj aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd jjj bbb", solution: "ddd jjj bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd jjj ccc", solution: "ddd jjj ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd jjj ddd", solution: "ddd jjj ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd jjj eee", solution: "ddd jjj eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd jjj fff", solution: "ddd jjj fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd jjj ggg", solution: "ddd jjj ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd jjj hhh", solution: "ddd jjj hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd jjj iii", solution: "ddd jjj iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("ddd jjj jjj", solution: "ddd jjj jjj", keep_order: true, glued: true, glue_strength: "punctuation")


        car << Expression.new("eee aaa aaa", solution: "eee aaa aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee aaa bbb", solution: "eee aaa bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee aaa ccc", solution: "eee aaa ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee aaa ddd", solution: "eee aaa ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee aaa eee", solution: "eee aaa eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee aaa fff", solution: "eee aaa fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee aaa ggg", solution: "eee aaa ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee aaa hhh", solution: "eee aaa hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee aaa iii", solution: "eee aaa iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee aaa jjj", solution: "eee aaa jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee bbb aaa", solution: "eee bbb aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee bbb bbb", solution: "eee bbb bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee bbb ccc", solution: "eee bbb ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee bbb ddd", solution: "eee bbb ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee bbb eee", solution: "eee bbb eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee bbb fff", solution: "eee bbb fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee bbb ggg", solution: "eee bbb ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee bbb hhh", solution: "eee bbb hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee bbb iii", solution: "eee bbb iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee bbb jjj", solution: "eee bbb jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee ccc aaa", solution: "eee ccc aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee ccc bbb", solution: "eee ccc bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee ccc ccc", solution: "eee ccc ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee ccc ddd", solution: "eee ccc ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee ccc eee", solution: "eee ccc eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee ccc fff", solution: "eee ccc fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee ccc ggg", solution: "eee ccc ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee ccc hhh", solution: "eee ccc hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee ccc iii", solution: "eee ccc iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee ccc jjj", solution: "eee ccc jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee ddd aaa", solution: "eee ddd aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee ddd bbb", solution: "eee ddd bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee ddd ccc", solution: "eee ddd ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee ddd ddd", solution: "eee ddd ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee ddd eee", solution: "eee ddd eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee ddd fff", solution: "eee ddd fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee ddd ggg", solution: "eee ddd ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee ddd hhh", solution: "eee ddd hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee ddd iii", solution: "eee ddd iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee ddd jjj", solution: "eee ddd jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee eee aaa", solution: "eee eee aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee eee bbb", solution: "eee eee bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee eee ccc", solution: "eee eee ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee eee ddd", solution: "eee eee ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee eee eee", solution: "eee eee eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee eee fff", solution: "eee eee fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee eee ggg", solution: "eee eee ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee eee hhh", solution: "eee eee hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee eee iii", solution: "eee eee iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee eee jjj", solution: "eee eee jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee fff aaa", solution: "eee fff aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee fff bbb", solution: "eee fff bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee fff ccc", solution: "eee fff ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee fff ddd", solution: "eee fff ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee fff eee", solution: "eee fff eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee fff fff", solution: "eee fff fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee fff ggg", solution: "eee fff ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee fff hhh", solution: "eee fff hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee fff iii", solution: "eee fff iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee fff jjj", solution: "eee fff jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee ggg aaa", solution: "eee ggg aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee ggg bbb", solution: "eee ggg bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee ggg ccc", solution: "eee ggg ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee ggg ddd", solution: "eee ggg ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee ggg eee", solution: "eee ggg eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee ggg fff", solution: "eee ggg fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee ggg ggg", solution: "eee ggg ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee ggg hhh", solution: "eee ggg hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee ggg iii", solution: "eee ggg iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee ggg jjj", solution: "eee ggg jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee hhh aaa", solution: "eee hhh aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee hhh bbb", solution: "eee hhh bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee hhh ccc", solution: "eee hhh ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee hhh ddd", solution: "eee hhh ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee hhh eee", solution: "eee hhh eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee hhh fff", solution: "eee hhh fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee hhh ggg", solution: "eee hhh ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee hhh hhh", solution: "eee hhh hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee hhh iii", solution: "eee hhh iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee hhh jjj", solution: "eee hhh jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee iii aaa", solution: "eee iii aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee iii bbb", solution: "eee iii bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee iii ccc", solution: "eee iii ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee iii ddd", solution: "eee iii ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee iii eee", solution: "eee iii eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee iii fff", solution: "eee iii fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee iii ggg", solution: "eee iii ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee iii hhh", solution: "eee iii hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee iii iii", solution: "eee iii iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee iii jjj", solution: "eee iii jjj", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee jjj aaa", solution: "eee jjj aaa", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee jjj bbb", solution: "eee jjj bbb", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee jjj ccc", solution: "eee jjj ccc", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee jjj ddd", solution: "eee jjj ddd", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee jjj eee", solution: "eee jjj eee", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee jjj fff", solution: "eee jjj fff", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee jjj ggg", solution: "eee jjj ggg", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee jjj hhh", solution: "eee jjj hhh", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee jjj iii", solution: "eee jjj iii", keep_order: true, glued: true, glue_strength: "punctuation")
        car << Expression.new("eee jjj jjj", solution: "eee jjj jjj", keep_order: true, glued: true, glue_strength: "punctuation")

        package
      end


      def test_entities

        expected = { interpretation: "entities", solution: "maison de campagne" }
        exception = assert_raises Minitest::Assertion do
          check_interpret("toto", expected)
        end
        assert exception.message.include?("Actual answer did not match on any interpretation")

        expected = { interpretation: "entities", solution: "maison de campagne" }
        check_interpret("before maison de campagne after", expected)

        expected = { interpretation: "entities", solution: "chemin du petit" }
        check_interpret("before chemin du petit after", expected)

        expected = { interpretation: "entities", solution: "chemin du petit bois" }
        check_interpret("before chemin du petit bois after", expected)

        expected = { interpretation: "entities", solution: "rivière de la belle etoile" }
        check_interpret("before rivière de la belle etoile after", expected)

        expected = { interpretation: "entities", solution: "aaa aaa bbb" }
        check_interpret("before aaa aaa bbb after", expected)

      end

      def test_entities_lemmatisation

        expected = { interpretation: "entities", solution: "maison de campagne" }
        check_interpret("before maisons de campagne after", expected)

        expected = { interpretation: "entities", solution: "maison de campagne" }
        check_interpret("before maison de campagnes after", expected)

        expected = { interpretation: "entities", solution: "maison de campagne" }
        check_interpret("before maisons de campagnes after", expected)

        expected = { interpretation: "entities", solution: "rivière de la belle etoile" }
        check_interpret("before rivières de la belle etoile after", expected)

      end


    end
  end

end
