/* 
 * Top level domains for Internet per www.iana.org
 * Copyright (c) Pertimm 2004 by Patrick Constant
 * Dev : March 2004
 * Version 1.0
*/
#include <logtld.h>
#include <loggen.h>


struct og_tld OgTld[] = {
  { 3, "nil", 	DOgTldnil,    0, "nil" },
  { 4, "aero",  DOgTldaero,   1, "air-transport industry" },
  { 3, "biz",   DOgTldbiz,    1, "businesses" },
  { 3, "com",   DOgTldcom,    1, "commercial" },
  { 4, "coop",  DOgTldcoop,   1, "cooperative associations" },
  { 4, "info",  DOgTldinfo,   1, "unspecified" },
  { 6, "museum",DOgTldmuseum, 1, "museums" },
  { 4, "name",	DOgTldname,   1, "individuals" },
  { 3, "net",	DOgTldnet,    1, "internet" },
  { 3, "org",	DOgTldorg,    1, "noncommercial" },
  { 3, "pro",	DOgTldpro,    1, "professionals" },
  { 3, "gov",	DOgTldgov,    1, "U.S. government" },
  { 3, "edu",	DOgTldedu,    1, "U.S. education" },
  { 3, "mil",	DOgTldmil,    1, "U.S. military" },
  { 3, "int",	DOgTldint,    1, "international" },
  { 2, "15", 	15,           0, "unused" },
  { 2, "16", 	16,           0, "unused" },
  { 2, "17", 	17,           0, "unused" },
  { 2, "18", 	18,           0, "unused" },
  { 2, "19", 	19,           0, "unused" },
  { 2, "20", 	20,           0, "unused" },
  { 2, "21", 	21,           0, "unused" },
  { 2, "22", 	22,           0, "unused" },
  { 2, "23", 	23,           0, "unused" },
  { 2, "24", 	24,           0, "unused" },
  { 2, "25", 	25,           0, "unused" },
  { 2, "26", 	26,           0, "unused" },
  { 2, "27", 	27,           0, "unused" },
  { 2, "28", 	28,           0, "unused" },
  { 2, "29", 	29,           0, "unused" },
  { 2, "ac", DOgTldac, 0, "Ascension Island" },
  { 2, "ad", DOgTldad, 0, "Andorra" },
  { 2, "ae", DOgTldae, 0, "United Arab Emirates" },
  { 2, "af", DOgTldaf, 0, "Afghanistan" },
  { 2, "ag", DOgTldag, 0, "Antigua and Barbuda" },
  { 2, "ai", DOgTldai, 0, "Anguilla" },
  { 2, "al", DOgTldal, 0, "Albania" },
  { 2, "am", DOgTldam, 0, "Armenia" },
  { 2, "an", DOgTldan, 0, "Netherlands Antilles" },
  { 2, "ao", DOgTldao, 0, "Angola" },
  { 2, "aq", DOgTldaq, 0, "Antarctica" },
  { 2, "ar", DOgTldar, 0, "Argentina" },
  { 2, "as", DOgTldas, 0, "American Samoa" },
  { 2, "at", DOgTldat, 0, "Austria" },
  { 2, "au", DOgTldau, 0, "Australia" },
  { 2, "aw", DOgTldaw, 0, "Aruba" },
  { 2, "az", DOgTldaz, 0, "Azerbaijan" },
  { 2, "ba", DOgTldba, 0, "Bosnia and Herzegovina" },
  { 2, "bb", DOgTldbb, 0, "Barbados" },
  { 2, "bd", DOgTldbd, 0, "Bangladesh" },
  { 2, "be", DOgTldbe, 0, "Belgium" },
  { 2, "bf", DOgTldbf, 0, "Burkina Faso" },
  { 2, "bg", DOgTldbg, 0, "Bulgaria" },
  { 2, "bh", DOgTldbh, 0, "Bahrain" },
  { 2, "bi", DOgTldbi, 0, "Burundi" },
  { 2, "bj", DOgTldbj, 0, "Benin" },
  { 2, "bm", DOgTldbm, 0, "Bermuda" },
  { 2, "bn", DOgTldbn, 0, "Brunei Darussalam" },
  { 2, "bo", DOgTldbo, 0, "Bolivia" },
  { 2, "br", DOgTldbr, 0, "Brazil" },
  { 2, "bs", DOgTldbs, 0, "Bahamas" },
  { 2, "bt", DOgTldbt, 0, "Bhutan" },
  { 2, "bv", DOgTldbv, 0, "Bouvet Island" },
  { 2, "bw", DOgTldbw, 0, "Botswana" },
  { 2, "by", DOgTldby, 0, "Belarus" },
  { 2, "bz", DOgTldbz, 0, "Belize" },
  { 2, "ca", DOgTldca, 0, "Canada" },
  { 2, "cc", DOgTldcc, 0, "Cocos (Keeling) Islands" },
  { 2, "cd", DOgTldcd, 0, "Congo, Democratic Republic of the" },
  { 2, "cf", DOgTldcf, 0, "Central African Republic" },
  { 2, "cg", DOgTldcg, 0, "Congo, Republic of" },
  { 2, "ch", DOgTldch, 0, "Switzerland" },
  { 2, "ci", DOgTldci, 0, "Cote d'Ivoire" },
  { 2, "ck", DOgTldck, 0, "Cook Islands" },
  { 2, "cl", DOgTldcl, 0, "Chile" },
  { 2, "cm", DOgTldcm, 0, "Cameroon" },
  { 2, "cn", DOgTldcn, 0, "China" },
  { 2, "co", DOgTldco, 0, "Colombia" },
  { 2, "cr", DOgTldcr, 0, "Costa Rica" },
  { 2, "cu", DOgTldcu, 0, "Cuba" },
  { 2, "cv", DOgTldcv, 0, "Cap Verde" },
  { 2, "cx", DOgTldcx, 0, "Christmas Island" },
  { 2, "cy", DOgTldcy, 0, "Cyprus" },
  { 2, "cz", DOgTldcz, 0, "Czech Republic" },
  { 2, "de", DOgTldde, 0, "Germany" },
  { 2, "dj", DOgTlddj, 0, "Djibouti" },
  { 2, "dk", DOgTlddk, 0, "Denmark" },
  { 2, "dm", DOgTlddm, 0, "Dominica" },
  { 2, "do", DOgTlddo, 0, "Dominican Republic" },
  { 2, "dz", DOgTlddz, 0, "Algeria" },
  { 2, "ec", DOgTldec, 0, "Ecuador" },
  { 2, "ee", DOgTldee, 0, "Estonia" },
  { 2, "eg", DOgTldeg, 0, "Egypt" },
  { 2, "eh", DOgTldeh, 0, "Western Sahara" },
  { 2, "er", DOgTlder, 0, "Eritrea" },
  { 2, "es", DOgTldes, 0, "Spain" },
  { 2, "et", DOgTldet, 0, "Ethiopia" },
  { 2, "fi", DOgTldfi, 0, "Finland" },
  { 2, "fj", DOgTldfj, 0, "Fiji" },
  { 2, "fk", DOgTldfk, 0, "Falkland Islands (Malvina)" },
  { 2, "fm", DOgTldfm, 0, "Micronesia, Federal State of" },
  { 2, "fo", DOgTldfo, 0, "Faroe Islands" },
  { 2, "fr", DOgTldfr, 0, "France" },
  { 2, "ga", DOgTldga, 0, "Gabon" },
  { 2, "gd", DOgTldgd, 0, "Grenada" },
  { 2, "ge", DOgTldge, 0, "Georgia" },
  { 2, "gf", DOgTldgf, 0, "French Guiana" },
  { 2, "gg", DOgTldgg, 0, "Guernsey" },
  { 2, "gh", DOgTldgh, 0, "Ghana" },
  { 2, "gi", DOgTldgi, 0, "Gibraltar" },
  { 2, "gl", DOgTldgl, 0, "Greenland" },
  { 2, "gm", DOgTldgm, 0, "Gambia" },
  { 2, "gn", DOgTldgn, 0, "Guinea" },
  { 2, "gp", DOgTldgp, 0, "Guadeloupe" },
  { 2, "gq", DOgTldgq, 0, "Equatorial Guinea" },
  { 2, "gr", DOgTldgr, 0, "Greece" },
  { 2, "gs", DOgTldgs, 0, "South Georgia and the South Sandwich Islands" },
  { 2, "gt", DOgTldgt, 0, "Guatemala" },
  { 2, "gu", DOgTldgu, 0, "Guam" },
  { 2, "gw", DOgTldgw, 0, "Guinea-Bissau" },
  { 2, "gy", DOgTldgy, 0, "Guyana" },
  { 2, "hk", DOgTldhk, 0, "Hong Kong" },
  { 2, "hm", DOgTldhm, 0, "Heard and McDonald Islands" },
  { 2, "hn", DOgTldhn, 0, "Honduras" },
  { 2, "hr", DOgTldhr, 0, "Croatia/Hrvatska" },
  { 2, "ht", DOgTldht, 0, "Haiti" },
  { 2, "hu", DOgTldhu, 0, "Hungary" },
  { 2, "id", DOgTldid, 0, "Indonesia" },
  { 2, "ie", DOgTldie, 0, "Ireland" },
  { 2, "il", DOgTldil, 0, "Israel" },
  { 2, "im", DOgTldim, 0, "Isle of Man" },
  { 2, "in", DOgTldin, 0, "India" },
  { 2, "io", DOgTldio, 0, "British Indian Ocean Territory" },
  { 2, "iq", DOgTldiq, 0, "Iraq" },
  { 2, "ir", DOgTldir, 0, "Iran (Islamic Republic of)" },
  { 2, "is", DOgTldis, 0, "Iceland" },
  { 2, "it", DOgTldit, 0, "Italy" },
  { 2, "je", DOgTldje, 0, "Jersey" },
  { 2, "jm", DOgTldjm, 0, "Jamaica" },
  { 2, "jo", DOgTldjo, 0, "Jordan" },
  { 2, "jp", DOgTldjp, 0, "Japan" },
  { 2, "ke", DOgTldke, 0, "Kenya" },
  { 2, "kg", DOgTldkg, 0, "Kyrgyzstan" },
  { 2, "kh", DOgTldkh, 0, "Cambodia" },
  { 2, "ki", DOgTldki, 0, "Kiribati" },
  { 2, "km", DOgTldkm, 0, "Comoros" },
  { 2, "kn", DOgTldkn, 0, "Saint Kitts and Nevis" },
  { 2, "kp", DOgTldkp, 0, "Korea, Democratic People's Republic" },
  { 2, "kr", DOgTldkr, 0, "Korea, Republic of" },
  { 2, "kw", DOgTldkw, 0, "Kuwait" },
  { 2, "ky", DOgTldky, 0, "Cayman Islands" },
  { 2, "kz", DOgTldkz, 0, "Kazakhstan" },
  { 2, "la", DOgTldla, 0, "Lao People's Democratic Republic" },
  { 2, "lb", DOgTldlb, 0, "Lebanon" },
  { 2, "lc", DOgTldlc, 0, "Saint Lucia" },
  { 2, "li", DOgTldli, 0, "Liechtenstein" },
  { 2, "lk", DOgTldlk, 0, "Sri Lanka" },
  { 2, "lr", DOgTldlr, 0, "Liberia" },
  { 2, "ls", DOgTldls, 0, "Lesotho" },
  { 2, "lt", DOgTldlt, 0, "Lithuania" },
  { 2, "lu", DOgTldlu, 0, "Luxembourg" },
  { 2, "lv", DOgTldlv, 0, "Latvia" },
  { 2, "ly", DOgTldly, 0, "Libyan Arab Jamahiriya" },
  { 2, "ma", DOgTldma, 0, "Morocco" },
  { 2, "mc", DOgTldmc, 0, "Monaco" },
  { 2, "md", DOgTldmd, 0, "Moldova, Republic of" },
  { 2, "mg", DOgTldmg, 0, "Madagascar" },
  { 2, "mh", DOgTldmh, 0, "Marshall Islands" },
  { 2, "mk", DOgTldmk, 0, "Macedonia, Former Yugoslav Republic" },
  { 2, "ml", DOgTldml, 0, "Mali" },
  { 2, "mm", DOgTldmm, 0, "Myanmar" },
  { 2, "mn", DOgTldmn, 0, "Mongolia" },
  { 2, "mo", DOgTldmo, 0, "Macau" },
  { 2, "mp", DOgTldmp, 0, "Northern Mariana Islands" },
  { 2, "mq", DOgTldmq, 0, "Martinique" },
  { 2, "mr", DOgTldmr, 0, "Mauritania" },
  { 2, "ms", DOgTldms, 0, "Montserrat" },
  { 2, "mt", DOgTldmt, 0, "Malta" },
  { 2, "mu", DOgTldmu, 0, "Mauritius" },
  { 2, "mv", DOgTldmv, 0, "Maldives" },
  { 2, "mw", DOgTldmw, 0, "Malawi" },
  { 2, "mx", DOgTldmx, 0, "Mexico" },
  { 2, "my", DOgTldmy, 0, "Malaysia" },
  { 2, "mz", DOgTldmz, 0, "Mozambique" },
  { 2, "na", DOgTldna, 0, "Namibia" },
  { 2, "nc", DOgTldnc, 0, "New Caledonia" },
  { 2, "ne", DOgTldne, 0, "Niger" },
  { 2, "nf", DOgTldnf, 0, "Norfolk Island" },
  { 2, "ng", DOgTldng, 0, "Nigeria" },
  { 2, "ni", DOgTldni, 0, "Nicaragua" },
  { 2, "nl", DOgTldnl, 0, "Netherlands" },
  { 2, "no", DOgTldno, 0, "Norway" },
  { 2, "np", DOgTldnp, 0, "Nepal" },
  { 2, "nr", DOgTldnr, 0, "Nauru" },
  { 2, "nu", DOgTldnu, 0, "Niue" },
  { 2, "nz", DOgTldnz, 0, "New Zealand" },
  { 2, "om", DOgTldom, 0, "Oman" },
  { 2, "pa", DOgTldpa, 0, "Panama" },
  { 2, "pe", DOgTldpe, 0, "Peru" },
  { 2, "pf", DOgTldpf, 0, "French Polynesia" },
  { 2, "pg", DOgTldpg, 0, "Papua New Guinea" },
  { 2, "ph", DOgTldph, 0, "Philippines" },
  { 2, "pk", DOgTldpk, 0, "Pakistan" },
  { 2, "pl", DOgTldpl, 0, "Poland" },
  { 2, "pm", DOgTldpm, 0, "St. Pierre and Miquelon" },
  { 2, "pn", DOgTldpn, 0, "Pitcairn Island" },
  { 2, "pr", DOgTldpr, 0, "Puerto Rico" },
  { 2, "ps", DOgTldps, 0, "Palestinian Territories" },
  { 2, "pt", DOgTldpt, 0, "Portugal" },
  { 2, "pw", DOgTldpw, 0, "Palau" },
  { 2, "py", DOgTldpy, 0, "Paraguay" },
  { 2, "qa", DOgTldqa, 0, "Qatar" },
  { 2, "re", DOgTldre, 0, "Reunion Island" },
  { 2, "ro", DOgTldro, 0, "Romania" },
  { 2, "ru", DOgTldru, 0, "Russian Federation" },
  { 2, "rw", DOgTldrw, 0, "Rwanda" },
  { 2, "sa", DOgTldsa, 0, "Saudi Arabia" },
  { 2, "sb", DOgTldsb, 0, "Solomon Islands" },
  { 2, "sc", DOgTldsc, 0, "Seychelles" },
  { 2, "sd", DOgTldsd, 0, "Sudan" },
  { 2, "se", DOgTldse, 0, "Sweden" },
  { 2, "sg", DOgTldsg, 0, "Singapore" },
  { 2, "sh", DOgTldsh, 0, "St. Helena" },
  { 2, "si", DOgTldsi, 0, "Slovenia" },
  { 2, "sj", DOgTldsj, 0, "Svalbard and Jan Mayen Islands" },
  { 2, "sk", DOgTldsk, 0, "Slovak Republic" },
  { 2, "sl", DOgTldsl, 0, "Sierra Leone" },
  { 2, "sm", DOgTldsm, 0, "San Marino" },
  { 2, "sn", DOgTldsn, 0, "Senegal" },
  { 2, "so", DOgTldso, 0, "Somalia" },
  { 2, "sr", DOgTldsr, 0, "Suriname" },
  { 2, "st", DOgTldst, 0, "Sao Tome and Principe" },
  { 2, "sv", DOgTldsv, 0, "El Salvador" },
  { 2, "sy", DOgTldsy, 0, "Syrian Arab Republic" },
  { 2, "sz", DOgTldsz, 0, "Swaziland" },
  { 2, "tc", DOgTldtc, 0, "Turks and Caicos Islands" },
  { 2, "td", DOgTldtd, 0, "Chad" },
  { 2, "tf", DOgTldtf, 0, "French Southern Territories" },
  { 2, "tg", DOgTldtg, 0, "Togo" },
  { 2, "th", DOgTldth, 0, "Thailand" },
  { 2, "tj", DOgTldtj, 0, "Tajikistan" },
  { 2, "tk", DOgTldtk, 0, "Tokelau" },
  { 2, "tm", DOgTldtm, 0, "Turkmenistan" },
  { 2, "tn", DOgTldtn, 0, "Tunisia" },
  { 2, "to", DOgTldto, 0, "Tonga" },
  { 2, "tp", DOgTldtp, 0, "East Timor" },
  { 2, "tr", DOgTldtr, 0, "Turkey" },
  { 2, "tt", DOgTldtt, 0, "Trinidad and Tobago" },
  { 2, "tv", DOgTldtv, 0, "Tuvalu" },
  { 2, "tw", DOgTldtw, 0, "Taiwan" },
  { 2, "tz", DOgTldtz, 0, "Tanzania" },
  { 2, "ua", DOgTldua, 0, "Ukraine" },
  { 2, "ug", DOgTldug, 0, "Uganda" },
  { 2, "uk", DOgTlduk, 0, "United Kingdom" },
  { 2, "um", DOgTldum, 0, "US Minor Outlying Islands" },
  { 2, "us", DOgTldus, 0, "United States" },
  { 2, "uy", DOgTlduy, 0, "Uruguay" },
  { 2, "uz", DOgTlduz, 0, "Uzbekistan" },
  { 2, "va", DOgTldva, 0, "Holy See (City Vatican State)" },
  { 2, "vc", DOgTldvc, 0, "Saint Vincent and the Grenadines" },
  { 2, "ve", DOgTldve, 0, "Venezuela" },
  { 2, "vg", DOgTldvg, 0, "Virgin Islands (British)" },
  { 2, "vi", DOgTldvi, 0, "Virgin Islands (USA)" },
  { 2, "vn", DOgTldvn, 0, "Vietnam" },
  { 2, "vu", DOgTldvu, 0, "Vanuatu" },
  { 2, "wf", DOgTldwf, 0, "Wallis and Futuna Islands" },
  { 2, "ws", DOgTldws, 0, "Western Samoa" },
  { 2, "ye", DOgTldye, 0, "Yemen" },
  { 2, "yt", DOgTldyt, 0, "Mayotte" },
  { 2, "yu", DOgTldyu, 0, "Yugoslavia" },
  { 2, "za", DOgTldza, 0, "South Africa" },
  { 2, "zm", DOgTldzm, 0, "Zambia" },
  { 2, "zw", DOgTldzw, 0, "Zimbabwe" },
  { 0, ""  , 0,        0, "" }
  };



PUBLIC(int) OgTldToInfo(char *s, struct og_tld **tld)
{
int i,code,found=0,is=strlen(s);
char erreur[DPcSzErr];

*tld=0;

for (i=0; OgTld[i].len; i++) {
  if (i != OgTld[i].code) {
    DPcSprintf(erreur,"OgTldToInfo: i (%d) != OgTld[i].code (%d)", i, OgTld[i].code);
    PcErr(-1,erreur); DPcErr;
    }
  if (is!=OgTld[i].len) continue;
  if (strcmp(s,OgTld[i].ch)) continue;
  found=1; break;
  }
if (!found) return(0);

*tld=OgTld+i;
code = OgTld[i].code;
if (DOgTldgMax <= code && code < DOgTldMin) return(0);
return(code);
}

