/*
 *  Header charset handling, contains all possible charsets
 *  Copyright (c) 2005 Pertimm, Inc. by Patrick Constant
 *  Dev: May 2005
 *  Version 1.0
*/
#ifndef _LOGCHSETALIVE_


/*
 *  Charset list is per http://www.iana.org/assignments/character_sets
 *  These are the official names for character sets that may be used in
 *  the Internet and may be referred to in Internet documentation.
 *  The name is the preferred MIME name, when available,
 *  and the value is the MIBenum. Naming convention is:
 *  "OgCharset_" followed by same exact name with '-' replace by '_'
*/
#define DOgCharset_ANSI_X3_4_1968                                   3
#define DOgCharset_ANSI_X3_4_1986                                   3
#define DOgCharset_ASCII                                            3
#define DOgCharset_cp367                                            3
#define DOgCharset_csASCII                                          3
#define DOgCharset_IBM367                                           3
#define DOgCharset_ISO646_US                                        3
#define DOgCharset_ISO_646_irv_1991                                 3
#define DOgCharset_iso_ir_6                                         3
#define DOgCharset_US_ASCII                                         3
#define DOgCharset_us                                               3
#define DOgCharset_CP819                                            4
#define DOgCharset_csISOLatin1                                      4
#define DOgCharset_IBM819                                           4
#define DOgCharset_ISO_8859_1                                       4
#define DOgCharset_ISO_8859_1                                       4
#define DOgCharset_ISO_8859_1_1987                                  4
#define DOgCharset_iso_ir_100                                       4
#define DOgCharset_l1                                               4
#define DOgCharset_latin1                                           4
#define DOgCharset_csISOLatin2                                      5
#define DOgCharset_ISO_8859_2                                       5
#define DOgCharset_ISO_8859_2                                       5
#define DOgCharset_ISO_8859_2_1987                                  5
#define DOgCharset_iso_ir_101                                       5
#define DOgCharset_l2                                               5
#define DOgCharset_latin2                                           5
#define DOgCharset_csISOLatin3                                      6
#define DOgCharset_ISO_8859_3                                       6
#define DOgCharset_ISO_8859_3                                       6
#define DOgCharset_ISO_8859_3_1988                                  6
#define DOgCharset_iso_ir_109                                       6
#define DOgCharset_l3                                               6
#define DOgCharset_latin3                                           6
#define DOgCharset_csISOLatin4                                      7
#define DOgCharset_ISO_8859_4                                       7
#define DOgCharset_ISO_8859_4                                       7
#define DOgCharset_ISO_8859_4_1988                                  7
#define DOgCharset_iso_ir_110                                       7
#define DOgCharset_l4                                               7
#define DOgCharset_latin4                                           7
#define DOgCharset_csISOLatinCyrillic                               8
#define DOgCharset_cyrillic                                         8
#define DOgCharset_ISO_8859_5                                       8
#define DOgCharset_ISO_8859_5                                       8
#define DOgCharset_ISO_8859_5_1988                                  8
#define DOgCharset_iso_ir_144                                       8
#define DOgCharset_ASMO_708                                         9
#define DOgCharset_arabic                                           9
#define DOgCharset_csISOLatinArabic                                 9
#define DOgCharset_ECMA_114                                         9
#define DOgCharset_ISO_8859_6                                       9
#define DOgCharset_ISO_8859_6                                       9
#define DOgCharset_ISO_8859_6_1987                                  9
#define DOgCharset_iso_ir_127                                       9
#define DOgCharset_csISOLatinGreek                                 10
#define DOgCharset_ECMA_118                                        10
#define DOgCharset_ELOT_928                                        10
#define DOgCharset_greek                                           10
#define DOgCharset_greek8                                          10
#define DOgCharset_ISO_8859_7                                      10
#define DOgCharset_ISO_8859_7                                      10
#define DOgCharset_ISO_8859_7_1987                                 10
#define DOgCharset_iso_ir_126                                      10
#define DOgCharset_csISOLatinHebrew                                11
#define DOgCharset_hebrew                                          11
#define DOgCharset_ISO_8859_8                                      11
#define DOgCharset_ISO_8859_8                                      11
#define DOgCharset_ISO_8859_8_1988                                 11
#define DOgCharset_iso_ir_138                                      11
#define DOgCharset_csISOLatin5                                     12
#define DOgCharset_ISO_8859_9                                      12
#define DOgCharset_ISO_8859_9                                      12
#define DOgCharset_ISO_8859_9_1989                                 12
#define DOgCharset_iso_ir_148                                      12
#define DOgCharset_l5                                              12
#define DOgCharset_latin5                                          12
#define DOgCharset_csISOLatin6                                     13
#define DOgCharset_ISO_8859_10                                     13
#define DOgCharset_ISO_8859_10_1992                                13
#define DOgCharset_iso_ir_157                                      13
#define DOgCharset_l6                                              13
#define DOgCharset_latin6                                          13
#define DOgCharset_csISOTextComm                                   14
#define DOgCharset_ISO_6937_2_add                                  14
#define DOgCharset_iso_ir_142                                      14
#define DOgCharset_csHalfWidthKatakana                             15
#define DOgCharset_JIS_X0201                                       15
#define DOgCharset_X0201                                           15
#define DOgCharset_csJISEncoding                                   16
#define DOgCharset_JIS_Encoding                                    16
#define DOgCharset_csShiftJIS                                      17
#define DOgCharset_MS_Kanji                                        17
#define DOgCharset_Shift_JIS                                       17
#define DOgCharset_csEUCPkdFmtJapanese                             18
#define DOgCharset_EUC_JP                                          18
#define DOgCharset_Extended_UNIX_Code_Packed_Format_for_Japanese   18
#define DOgCharset_csEUCFixWidJapanese                             19
#define DOgCharset_Extended_UNIX_Code_Fixed_Width_for_Japanese     19
#define DOgCharset_BS_4730                                         20
#define DOgCharset_csISO4UnitedKingdom                             20
#define DOgCharset_gb                                              20
#define DOgCharset_ISO646_GB                                       20
#define DOgCharset_iso_ir_4                                        20
#define DOgCharset_uk                                              20
#define DOgCharset_csISO11SwedishForNames                          21
#define DOgCharset_ISO646_SE2                                      21
#define DOgCharset_iso_ir_11                                       21
#define DOgCharset_SEN_850200_C                                    21
#define DOgCharset_se2                                             21
#define DOgCharset_csISO15Italian                                  22
#define DOgCharset_ISO646_IT                                       22
#define DOgCharset_IT                                              22
#define DOgCharset_iso_ir_15                                       22
#define DOgCharset_csISO17Spanish                                  23
#define DOgCharset_ES                                              23
#define DOgCharset_ISO646_ES                                       23
#define DOgCharset_iso_ir_17                                       23
#define DOgCharset_csISO21German                                   24
#define DOgCharset_DIN_66003                                       24
#define DOgCharset_de                                              24
#define DOgCharset_ISO646_DE                                       24
#define DOgCharset_iso_ir_21                                       24
#define DOgCharset_csISO60DanishNorwegian                          25
#define DOgCharset_csISO60Norwegian1                               25
#define DOgCharset_ISO646_NO                                       25
#define DOgCharset_iso_ir_60                                       25
#define DOgCharset_NS_4551_1                                       25
#define DOgCharset_no                                              25
#define DOgCharset_csISO69French                                   26
#define DOgCharset_fr                                              26
#define DOgCharset_ISO646_FR                                       26
#define DOgCharset_iso_ir_69                                       26
#define DOgCharset_NF_Z_62_010                                     26
#define DOgCharset_csISO10646UTF1                                  27
#define DOgCharset_ISO_10646_UTF_1                                 27
#define DOgCharset_csISO646basic1983                               28
#define DOgCharset_ISO_646_basic_1983                              28
#define DOgCharset_ref                                             28
#define DOgCharset_csINVARIANT                                     29
#define DOgCharset_INVARIANT                                       29
#define DOgCharset_csISO2IntlRefVersion                            30
#define DOgCharset_ISO_646_irv_1983                                30
#define DOgCharset_irv                                             30
#define DOgCharset_iso_ir_2                                        30
#define DOgCharset_csNATSSEFI                                      31
#define DOgCharset_iso_ir_8_1                                      31
#define DOgCharset_NATS_SEFI                                       31
#define DOgCharset_csNATSSEFIADD                                   32
#define DOgCharset_iso_ir_8_2                                      32
#define DOgCharset_NATS_SEFI_ADD                                   32
#define DOgCharset_csNATSDANO                                      33
#define DOgCharset_iso_ir_9_1                                      33
#define DOgCharset_NATS_DANO                                       33
#define DOgCharset_csNATSDANOADD                                   34
#define DOgCharset_iso_ir_9_2                                      34
#define DOgCharset_NATS_DANO_ADD                                   34
#define DOgCharset_csISO10Swedish                                  35
#define DOgCharset_FI                                              35
#define DOgCharset_ISO646_FI                                       35
#define DOgCharset_ISO646_SE                                       35
#define DOgCharset_iso_ir_10                                       35
#define DOgCharset_SEN_850200_B                                    35
#define DOgCharset_se                                              35
#define DOgCharset_csKSC56011987                                   36
#define DOgCharset_iso_ir_149                                      36
#define DOgCharset_KSC_5601                                        36
#define DOgCharset_KS_C_5601_1987                                  36
#define DOgCharset_KS_C_5601_1989                                  36
#define DOgCharset_korean                                          36
#define DOgCharset_csISO2022KR                                     37
#define DOgCharset_ISO_2022_KR                                     37
#define DOgCharset_csEUCKR                                         38
#define DOgCharset_EUC_KR                                          38
#define DOgCharset_csISO2022JP                                     39
#define DOgCharset_ISO_2022_JP                                     39
#define DOgCharset_csISO2022JP2                                    40
#define DOgCharset_ISO_2022_JP_2                                   40
#define DOgCharset_csISO13JISC6220jp                               41
#define DOgCharset_iso_ir_13                                       41
#define DOgCharset_JIS_C6220_1969                                  41
#define DOgCharset_JIS_C6220_1969_jp                               41
#define DOgCharset_katakana                                        41
#define DOgCharset_x0201_7                                         41
#define DOgCharset_csISO14JISC6220ro                               42
#define DOgCharset_ISO646_JP                                       42
#define DOgCharset_iso_ir_14                                       42
#define DOgCharset_JIS_C6220_1969_ro                               42
#define DOgCharset_jp                                              42
#define DOgCharset_csISO16Portuguese                               43
#define DOgCharset_ISO646_PT                                       43
#define DOgCharset_iso_ir_16                                       43
#define DOgCharset_PT                                              43
#define DOgCharset_csISO18Greek7Old                                44
#define DOgCharset_greek7_old                                      44
#define DOgCharset_iso_ir_18                                       44
#define DOgCharset_csISO19LatinGreek                               45
#define DOgCharset_iso_ir_19                                       45
#define DOgCharset_latin_greek                                     45
#define DOgCharset_csISO25French                                   46
#define DOgCharset_ISO646_FR1                                      46
#define DOgCharset_iso_ir_25                                       46
#define DOgCharset_NF_Z_62_010__1973_                              46
#define DOgCharset_csISO27LatinGreek1                              47
#define DOgCharset_iso_ir_27                                       47
#define DOgCharset_Latin_greek_1                                   47
#define DOgCharset_csISO5427Cyrillic                               48
#define DOgCharset_ISO_5427                                        48
#define DOgCharset_iso_ir_37                                       48
#define DOgCharset_csISO42JISC62261978                             49
#define DOgCharset_iso_ir_42                                       49
#define DOgCharset_JIS_C6226_1978                                  49
#define DOgCharset_BS_viewdata                                     50
#define DOgCharset_csISO47BSViewdata                               50
#define DOgCharset_iso_ir_47                                       50
#define DOgCharset_csISO49INIS                                     51
#define DOgCharset_INIS                                            51
#define DOgCharset_iso_ir_49                                       51
#define DOgCharset_csISO50INIS8                                    52
#define DOgCharset_INIS_8                                          52
#define DOgCharset_iso_ir_50                                       52
#define DOgCharset_csISO51INISCyrillic                             53
#define DOgCharset_INIS_cyrillic                                   53
#define DOgCharset_iso_ir_51                                       53
#define DOgCharset_ISO5427Cyrillic1981                             54
#define DOgCharset_ISO_5427_1981                                   54
#define DOgCharset_iso_ir_54                                       54
#define DOgCharset_csISO5428Greek                                  55
#define DOgCharset_ISO_5428_1980                                   55
#define DOgCharset_iso_ir_55                                       55
#define DOgCharset_cn                                              56
#define DOgCharset_csISO57GB1988                                   56
#define DOgCharset_GB_1988_80                                      56
#define DOgCharset_ISO646_CN                                       56
#define DOgCharset_iso_ir_57                                       56
#define DOgCharset_chinese                                         57
#define DOgCharset_csISO58GB231280                                 57
#define DOgCharset_GB_2312_80                                      57
#define DOgCharset_iso_ir_58                                       57
#define DOgCharset_csISO61Norwegian2                               58
#define DOgCharset_ISO646_NO2                                      58
#define DOgCharset_iso_ir_61                                       58
#define DOgCharset_NS_4551_2                                       58
#define DOgCharset_no2                                             58
#define DOgCharset_csISO70VideotexSupp1                            59
#define DOgCharset_iso_ir_70                                       59
#define DOgCharset_videotex_suppl                                  59
#define DOgCharset_csISO84Portuguese2                              60
#define DOgCharset_ISO646_PT2                                      60
#define DOgCharset_iso_ir_84                                       60
#define DOgCharset_PT2                                             60
#define DOgCharset_csISO85Spanish2                                 61
#define DOgCharset_ES2                                             61
#define DOgCharset_ISO646_ES2                                      61
#define DOgCharset_iso_ir_85                                       61
#define DOgCharset_csISO86Hungarian                                62
#define DOgCharset_hu                                              62
#define DOgCharset_ISO646_HU                                       62
#define DOgCharset_iso_ir_86                                       62
#define DOgCharset_MSZ_7795_3                                      62
#define DOgCharset_csISO87JISX0208                                 63
#define DOgCharset_iso_ir_87                                       63
#define DOgCharset_JIS_C6226_1983                                  63
#define DOgCharset_JIS_X0208_1983                                  63
#define DOgCharset_x0208                                           63
#define DOgCharset_csISO88Greek7                                   64
#define DOgCharset_greek7                                          64
#define DOgCharset_iso_ir_88                                       64
#define DOgCharset_ASMO_449                                        65
#define DOgCharset_arabic7                                         65
#define DOgCharset_csISO89ASMO449                                  65
#define DOgCharset_ISO_9036                                        65
#define DOgCharset_iso_ir_89                                       65
#define DOgCharset_csISO90                                         66
#define DOgCharset_iso_ir_90                                       66
#define DOgCharset_csISO91JISC62291984a                            67
#define DOgCharset_iso_ir_91                                       67
#define DOgCharset_JIS_C6229_1984_a                                67
#define DOgCharset_jp_ocr_a                                        67
#define DOgCharset_csISO92JISC62991984b                            68
#define DOgCharset_ISO646_JP_OCR_B                                 68
#define DOgCharset_iso_ir_92                                       68
#define DOgCharset_JIS_C6229_1984_b                                68
#define DOgCharset_jp_ocr_b                                        68
#define DOgCharset_csISO93JIS62291984badd                          69
#define DOgCharset_iso_ir_93                                       69
#define DOgCharset_JIS_C6229_1984_b_add                            69
#define DOgCharset_jp_ocr_b_add                                    69
#define DOgCharset_csISO94JIS62291984hand                          70
#define DOgCharset_iso_ir_94                                       70
#define DOgCharset_JIS_C6229_1984_hand                             70
#define DOgCharset_jp_ocr_hand                                     70
#define DOgCharset_csISO95JIS62291984handadd                       71
#define DOgCharset_iso_ir_95                                       71
#define DOgCharset_JIS_C6229_1984_hand_add                         71
#define DOgCharset_jp_ocr_hand_add                                 71
#define DOgCharset_csISO96JISC62291984kana                         72
#define DOgCharset_iso_ir_96                                       72
#define DOgCharset_JIS_C6229_1984_kana                             72
#define DOgCharset_csISO2033                                       73
#define DOgCharset_e13b                                            73
#define DOgCharset_ISO_2033_1983                                   73
#define DOgCharset_iso_ir_98                                       73
#define DOgCharset_ANSI_X3_110_1983                                74
#define DOgCharset_CSA_T500_1983                                   74
#define DOgCharset_csISO99NAPLPS                                   74
#define DOgCharset_iso_ir_99                                       74
#define DOgCharset_NAPLPS                                          74
#define DOgCharset_csISO102T617bit                                 75
#define DOgCharset_iso_ir_102                                      75
#define DOgCharset_T_61_7bit                                       75
#define DOgCharset_csISO103T618bit                                 76
#define DOgCharset_iso_ir_103                                      76
#define DOgCharset_T_61                                            76
#define DOgCharset_T_61_8bit                                       76
#define DOgCharset_csISO111ECMACyrillic                            77
#define DOgCharset_ECMA_cyrillic                                   77
#define DOgCharset_iso_ir_111                                      77
#define DOgCharset_KOI8_E                                          77
#define DOgCharset_CSA_Z243_4_1985_1                               78
#define DOgCharset_ca                                              78
#define DOgCharset_csa7_1                                          78
#define DOgCharset_csISO121Canadian1                               78
#define DOgCharset_ISO646_CA                                       78
#define DOgCharset_iso_ir_121                                      78
#define DOgCharset_CSA_Z243_4_1985_2                               79
#define DOgCharset_csa7_2                                          79
#define DOgCharset_csISO122Canadian2                               79
#define DOgCharset_ISO646_CA2                                      79
#define DOgCharset_iso_ir_122                                      79
#define DOgCharset_CSA_Z243_4_1985_gr                              80
#define DOgCharset_csISO123CSAZ24341985gr                          80
#define DOgCharset_iso_ir_123                                      80
#define DOgCharset_csISO88596E                                     81
#define DOgCharset_ISO_8859_6_E                                    81
#define DOgCharset_ISO_8859_6_E                                    81
#define DOgCharset_csISO88596I                                     82
#define DOgCharset_ISO_8859_6_I                                    82
#define DOgCharset_ISO_8859_6_I                                    82
#define DOgCharset_csISO128T101G2                                  83
#define DOgCharset_iso_ir_128                                      83
#define DOgCharset_T_101_G2                                        83
#define DOgCharset_csISO88598E                                     84
#define DOgCharset_ISO_8859_8_E                                    84
#define DOgCharset_ISO_8859_8_E                                    84
#define DOgCharset_csISO88598I                                     85
#define DOgCharset_ISO_8859_8_I                                    85
#define DOgCharset_ISO_8859_8_I                                    85
#define DOgCharset_CSN_369103                                      86
#define DOgCharset_csISO139CSN369103                               86
#define DOgCharset_iso_ir_139                                      86
#define DOgCharset_csISO141JUSIB1002                               87
#define DOgCharset_ISO646_YU                                       87
#define DOgCharset_iso_ir_141                                      87
#define DOgCharset_JUS_I_B1_002                                    87
#define DOgCharset_js                                              87
#define DOgCharset_yu                                              87
#define DOgCharset_csISO143IECP271                                 88
#define DOgCharset_IEC_P27_1                                       88
#define DOgCharset_iso_ir_143                                      88
#define DOgCharset_csISO146Serbian                                 89
#define DOgCharset_iso_ir_146                                      89
#define DOgCharset_JUS_I_B1_003_serb                               89
#define DOgCharset_serbian                                         89
#define DOgCharset_csISO147Macedonian                              90
#define DOgCharset_iso_ir_147                                      90
#define DOgCharset_JUS_I_B1_003_mac                                90
#define DOgCharset_macedonian                                      90
#define DOgCharset_csISO150                                        91
#define DOgCharset_csISO150GreekCCITT                              91
#define DOgCharset_greek_ccitt                                     91
#define DOgCharset_iso_ir_150                                      91
#define DOgCharset_csISO151Cuba                                    92
#define DOgCharset_cuba                                            92
#define DOgCharset_ISO646_CU                                       92
#define DOgCharset_iso_ir_151                                      92
#define DOgCharset_NC_NC00_10_81                                   92
#define DOgCharset_csISO6937Add                                    93
#define DOgCharset_ISO_6937_2_25                                   93
#define DOgCharset_iso_ir_152                                      93
#define DOgCharset_csISO153GOST1976874                             94
#define DOgCharset_GOST_19768_74                                   94
#define DOgCharset_iso_ir_153                                      94
#define DOgCharset_ST_SEV_358_88                                   94
#define DOgCharset_csISO8859Supp                                   95
#define DOgCharset_ISO_8859_supp                                   95
#define DOgCharset_iso_ir_154                                      95
#define DOgCharset_latin1_2_5                                      95
#define DOgCharset_csISO10367Box                                   96
#define DOgCharset_ISO_10367_box                                   96
#define DOgCharset_iso_ir_155                                      96
#define DOgCharset_csISO158Lap                                     97
#define DOgCharset_iso_ir_158                                      97
#define DOgCharset_lap                                             97
#define DOgCharset_latin_lap                                       97
#define DOgCharset_csISO159JISX02121990                            98
#define DOgCharset_iso_ir_159                                      98
#define DOgCharset_JIS_X0212_1990                                  98
#define DOgCharset_x0212                                           98
#define DOgCharset_csISO646Danish                                  99
#define DOgCharset_DS2089                                          99
#define DOgCharset_DS_2089                                         99
#define DOgCharset_dk                                              99
#define DOgCharset_ISO646_DK                                       99
#define DOgCharset_csUSDK                                         100
#define DOgCharset_us_dk                                          100
#define DOgCharset_csDKUS                                         101
#define DOgCharset_dk_us                                          101
#define DOgCharset_csKSC5636                                      102
#define DOgCharset_ISO646_KR                                      102
#define DOgCharset_KSC5636                                        102
#define DOgCharset_csUnicode11UTF7                                103
#define DOgCharset_UNICODE_1_1_UTF_7                              103
#define DOgCharset_ISO_2022_CN                                    104
#define DOgCharset_ISO_2022_CN_EXT                                105
#define DOgCharset_UTF_8                                          106
#define DOgCharset_ISO_8859_13                                    109
#define DOgCharset_ISO_8859_14                                    110
#define DOgCharset_ISO_8859_14                                    110
#define DOgCharset_ISO_8859_14_1998                               110
#define DOgCharset_iso_celtic                                     110
#define DOgCharset_iso_ir_199                                     110
#define DOgCharset_l8                                             110
#define DOgCharset_latin8                                         110
#define DOgCharset_ISO_8859_15                                    111
#define DOgCharset_ISO_8859_15                                    111
#define DOgCharset_Latin_9                                        111
#define DOgCharset_ISO_8859_16                                    112
#define DOgCharset_ISO_8859_16                                    112
#define DOgCharset_ISO_8859_16_2001                               112
#define DOgCharset_iso_ir_226                                     112
#define DOgCharset_l10                                            112
#define DOgCharset_latin10                                        112
#define DOgCharset_CP936                                          113
#define DOgCharset_GBK                                            113
#define DOgCharset_MS936                                          113
#define DOgCharset_windows_936                                    113
#define DOgCharset_GB18030                                        114
#define DOgCharset_OSD_EBCDIC_DF04_15                             115
#define DOgCharset_OSD_EBCDIC_DF03_IRV                            116
#define DOgCharset_OSD_EBCDIC_DF04_1                              117
#define DOgCharset_csUnicode                                     1000
#define DOgCharset_ISO_10646_UCS_2                               1000
#define DOgCharset_csUCS4                                        1001
#define DOgCharset_ISO_10646_UCS_4                               1001
#define DOgCharset_csUnicodeASCII                                1002
#define DOgCharset_ISO_10646_UCS_Basic                           1002
#define DOgCharset_csUnicodeLatin1                               1003
#define DOgCharset_ISO_10646                                     1003
#define DOgCharset_ISO_10646_Unicode_Latin1                      1003
#define DOgCharset_ISO_10646_J_1                                 1004
#define DOgCharset_csUnicodeIBM1261                              1005
#define DOgCharset_ISO_Unicode_IBM_1261                          1005
#define DOgCharset_csUnicodeIBM1268                              1006
#define DOgCharset_ISO_Unicode_IBM_1268                          1006
#define DOgCharset_csUnicodeIBM1276                              1007
#define DOgCharset_ISO_Unicode_IBM_1276                          1007
#define DOgCharset_csUnicodeIBM1264                              1008
#define DOgCharset_ISO_Unicode_IBM_1264                          1008
#define DOgCharset_csUnicodeIBM1265                              1009
#define DOgCharset_ISO_Unicode_IBM_1265                          1009
#define DOgCharset_csUnicode11                                   1010
#define DOgCharset_UNICODE_1_1                                   1010
#define DOgCharset_SCSU                                          1011
#define DOgCharset_UTF_7                                         1012
#define DOgCharset_UTF_16BE                                      1013
#define DOgCharset_UTF_16LE                                      1014
#define DOgCharset_UTF_16                                        1015
#define DOgCharset_CESU_8                                        1016
#define DOgCharset_csCESU_8                                      1016
#define DOgCharset_UTF_32                                        1017
#define DOgCharset_UTF_32BE                                      1018
#define DOgCharset_UTF_32LE                                      1019
#define DOgCharset_BOCU_1                                        1020
#define DOgCharset_csBOCU_1                                      1020
#define DOgCharset_csWindows30Latin1                             2000
#define DOgCharset_ISO_8859_1_Windows_3_0_Latin_1                2000
#define DOgCharset_csWindows31Latin1                             2001
#define DOgCharset_ISO_8859_1_Windows_3_1_Latin_1                2001
#define DOgCharset_csWindows31Latin2                             2002
#define DOgCharset_ISO_8859_2_Windows_Latin_2                    2002
#define DOgCharset_csWindows31Latin5                             2003
#define DOgCharset_ISO_8859_9_Windows_Latin_5                    2003
#define DOgCharset_csHPRoman8                                    2004
#define DOgCharset_hp_roman8                                     2004
#define DOgCharset_r8                                            2004
#define DOgCharset_roman8                                        2004
#define DOgCharset_Adobe_Standard_Encoding                       2005
#define DOgCharset_csAdobeStandardEncoding                       2005
#define DOgCharset_csVenturaUS                                   2006
#define DOgCharset_Ventura_US                                    2006
#define DOgCharset_csVenturaInternational                        2007
#define DOgCharset_Ventura_International                         2007
#define DOgCharset_csDECMCS                                      2008
#define DOgCharset_DEC_MCS                                       2008
#define DOgCharset_dec                                           2008
#define DOgCharset_850                                           2009
#define DOgCharset_cp850                                         2009
#define DOgCharset_csPC850Multilingual                           2009
#define DOgCharset_IBM850                                        2009
#define DOgCharset_852                                           2010
#define DOgCharset_cp852                                         2010
#define DOgCharset_csPCp852                                      2010
#define DOgCharset_IBM852                                        2010
#define DOgCharset_437                                           2011
#define DOgCharset_cp437                                         2011
#define DOgCharset_csPC8CodePage437                              2011
#define DOgCharset_IBM437                                        2011
#define DOgCharset_csPC8DanishNorwegian                          2012
#define DOgCharset_PC8_Danish_Norwegian                          2012
#define DOgCharset_862                                           2013
#define DOgCharset_cp862                                         2013
#define DOgCharset_csPC862LatinHebrew                            2013
#define DOgCharset_IBM862                                        2013
#define DOgCharset_csPC8Turkish                                  2014
#define DOgCharset_PC8_Turkish                                   2014
#define DOgCharset_csIBMSymbols                                  2015
#define DOgCharset_IBM_Symbols                                   2015
#define DOgCharset_csIBMThai                                     2016
#define DOgCharset_IBM_Thai                                      2016
#define DOgCharset_csHPLegal                                     2017
#define DOgCharset_HP_Legal                                      2017
#define DOgCharset_csHPPiFont                                    2018
#define DOgCharset_HP_Pi_font                                    2018
#define DOgCharset_csHPMath8                                     2019
#define DOgCharset_HP_Math8                                      2019
#define DOgCharset_Adobe_Symbol_Encoding                         2020
#define DOgCharset_csHPPSMath                                    2020
#define DOgCharset_csHPDesktop                                   2021
#define DOgCharset_HP_DeskTop                                    2021
#define DOgCharset_csVenturaMath                                 2022
#define DOgCharset_Ventura_Math                                  2022
#define DOgCharset_csMicrosoftPublishing                         2023
#define DOgCharset_Microsoft_Publishing                          2023
#define DOgCharset_csWindows31J                                  2024
#define DOgCharset_Windows_31J                                   2024
#define DOgCharset_csGB2312                                      2025
#define DOgCharset_GB2312                                        2025
#define DOgCharset_Big5                                          2026
#define DOgCharset_csBig5                                        2026
#define DOgCharset_csMacintosh                                   2027
#define DOgCharset_mac                                           2027
#define DOgCharset_macintosh                                     2027
#define DOgCharset_cp037                                         2028
#define DOgCharset_csIBM037                                      2028
#define DOgCharset_ebcdic_cp_ca                                  2028
#define DOgCharset_ebcdic_cp_nl                                  2028
#define DOgCharset_ebcdic_cp_us                                  2028
#define DOgCharset_ebcdic_cp_wt                                  2028
#define DOgCharset_IBM037                                        2028
#define DOgCharset_cp038                                         2029
#define DOgCharset_csIBM038                                      2029
#define DOgCharset_EBCDIC_INT                                    2029
#define DOgCharset_IBM038                                        2029
#define DOgCharset_CP273                                         2030
#define DOgCharset_csIBM273                                      2030
#define DOgCharset_IBM273                                        2030
#define DOgCharset_CP274                                         2031
#define DOgCharset_csIBM274                                      2031
#define DOgCharset_EBCDIC_BE                                     2031
#define DOgCharset_IBM274                                        2031
#define DOgCharset_cp275                                         2032
#define DOgCharset_csIBM275                                      2032
#define DOgCharset_EBCDIC_BR                                     2032
#define DOgCharset_IBM275                                        2032
#define DOgCharset_csIBM277                                      2033
#define DOgCharset_EBCDIC_CP_DK                                  2033
#define DOgCharset_EBCDIC_CP_NO                                  2033
#define DOgCharset_IBM277                                        2033
#define DOgCharset_CP278                                         2034
#define DOgCharset_csIBM278                                      2034
#define DOgCharset_ebcdic_cp_fi                                  2034
#define DOgCharset_ebcdic_cp_se                                  2034
#define DOgCharset_IBM278                                        2034
#define DOgCharset_CP280                                         2035
#define DOgCharset_csIBM280                                      2035
#define DOgCharset_ebcdic_cp_it                                  2035
#define DOgCharset_IBM280                                        2035
#define DOgCharset_cp281                                         2036
#define DOgCharset_csIBM281                                      2036
#define DOgCharset_EBCDIC_JP_E                                   2036
#define DOgCharset_IBM281                                        2036
#define DOgCharset_CP284                                         2037
#define DOgCharset_csIBM284                                      2037
#define DOgCharset_ebcdic_cp_es                                  2037
#define DOgCharset_IBM284                                        2037
#define DOgCharset_CP285                                         2038
#define DOgCharset_csIBM285                                      2038
#define DOgCharset_ebcdic_cp_gb                                  2038
#define DOgCharset_IBM285                                        2038
#define DOgCharset_cp290                                         2039
#define DOgCharset_csIBM290                                      2039
#define DOgCharset_EBCDIC_JP_kana                                2039
#define DOgCharset_IBM290                                        2039
#define DOgCharset_cp297                                         2040
#define DOgCharset_csIBM297                                      2040
#define DOgCharset_ebcdic_cp_fr                                  2040
#define DOgCharset_IBM297                                        2040
#define DOgCharset_cp420                                         2041
#define DOgCharset_csIBM420                                      2041
#define DOgCharset_ebcdic_cp_ar1                                 2041
#define DOgCharset_IBM420                                        2041
#define DOgCharset_cp423                                         2042
#define DOgCharset_csIBM423                                      2042
#define DOgCharset_ebcdic_cp_gr                                  2042
#define DOgCharset_IBM423                                        2042
#define DOgCharset_cp424                                         2043
#define DOgCharset_csIBM424                                      2043
#define DOgCharset_ebcdic_cp_he                                  2043
#define DOgCharset_IBM424                                        2043
#define DOgCharset_CP500                                         2044
#define DOgCharset_csIBM500                                      2044
#define DOgCharset_ebcdic_cp_be                                  2044
#define DOgCharset_ebcdic_cp_ch                                  2044
#define DOgCharset_IBM500                                        2044
#define DOgCharset_851                                           2045
#define DOgCharset_cp851                                         2045
#define DOgCharset_csIBM851                                      2045
#define DOgCharset_IBM851                                        2045
#define DOgCharset_855                                           2046
#define DOgCharset_cp855                                         2046
#define DOgCharset_csIBM855                                      2046
#define DOgCharset_IBM855                                        2046
#define DOgCharset_857                                           2047
#define DOgCharset_cp857                                         2047
#define DOgCharset_csIBM857                                      2047
#define DOgCharset_IBM857                                        2047
#define DOgCharset_860                                           2048
#define DOgCharset_cp860                                         2048
#define DOgCharset_csIBM860                                      2048
#define DOgCharset_IBM860                                        2048
#define DOgCharset_861                                           2049
#define DOgCharset_cp_is                                         2049
#define DOgCharset_cp861                                         2049
#define DOgCharset_csIBM861                                      2049
#define DOgCharset_IBM861                                        2049
#define DOgCharset_863                                           2050
#define DOgCharset_cp863                                         2050
#define DOgCharset_csIBM863                                      2050
#define DOgCharset_IBM863                                        2050
#define DOgCharset_cp864                                         2051
#define DOgCharset_csIBM864                                      2051
#define DOgCharset_IBM864                                        2051
#define DOgCharset_865                                           2052
#define DOgCharset_cp865                                         2052
#define DOgCharset_csIBM865                                      2052
#define DOgCharset_IBM865                                        2052
#define DOgCharset_CP868                                         2053
#define DOgCharset_cp_ar                                         2053
#define DOgCharset_csIBM868                                      2053
#define DOgCharset_IBM868                                        2053
#define DOgCharset_869                                           2054
#define DOgCharset_cp_gr                                         2054
#define DOgCharset_cp869                                         2054
#define DOgCharset_csIBM869                                      2054
#define DOgCharset_IBM869                                        2054
#define DOgCharset_CP870                                         2055
#define DOgCharset_csIBM870                                      2055
#define DOgCharset_ebcdic_cp_roece                               2055
#define DOgCharset_ebcdic_cp_yu                                  2055
#define DOgCharset_IBM870                                        2055
#define DOgCharset_CP871                                         2056
#define DOgCharset_csIBM871                                      2056
#define DOgCharset_ebcdic_cp_is                                  2056
#define DOgCharset_IBM871                                        2056
#define DOgCharset_cp880                                         2057
#define DOgCharset_csIBM880                                      2057
#define DOgCharset_EBCDIC_Cyrillic                               2057
#define DOgCharset_IBM880                                        2057
#define DOgCharset_cp891                                         2058
#define DOgCharset_csIBM891                                      2058
#define DOgCharset_IBM891                                        2058
#define DOgCharset_cp903                                         2059
#define DOgCharset_csIBM903                                      2059
#define DOgCharset_IBM903                                        2059
#define DOgCharset_904                                           2060
#define DOgCharset_cp904                                         2060
#define DOgCharset_csIBBM904                                     2060
#define DOgCharset_IBM904                                        2060
#define DOgCharset_CP905                                         2061
#define DOgCharset_csIBM905                                      2061
#define DOgCharset_ebcdic_cp_tr                                  2061
#define DOgCharset_IBM905                                        2061
#define DOgCharset_CP918                                         2062
#define DOgCharset_csIBM918                                      2062
#define DOgCharset_ebcdic_cp_ar2                                 2062
#define DOgCharset_IBM918                                        2062
#define DOgCharset_CP1026                                        2063
#define DOgCharset_csIBM1026                                     2063
#define DOgCharset_IBM1026                                       2063
#define DOgCharset_csIBMEBCDICATDE                               2064
#define DOgCharset_EBCDIC_AT_DE                                  2064
#define DOgCharset_csEBCDICATDEA                                 2065
#define DOgCharset_EBCDIC_AT_DE_A                                2065
#define DOgCharset_csEBCDICCAFR                                  2066
#define DOgCharset_EBCDIC_CA_FR                                  2066
#define DOgCharset_csEBCDICDKNO                                  2067
#define DOgCharset_EBCDIC_DK_NO                                  2067
#define DOgCharset_csEBCDICDKNOA                                 2068
#define DOgCharset_EBCDIC_DK_NO_A                                2068
#define DOgCharset_csEBCDICFISE                                  2069
#define DOgCharset_EBCDIC_FI_SE                                  2069
#define DOgCharset_csEBCDICFISEA                                 2070
#define DOgCharset_EBCDIC_FI_SE_A                                2070
#define DOgCharset_csEBCDICFR                                    2071
#define DOgCharset_EBCDIC_FR                                     2071
#define DOgCharset_csEBCDICIT                                    2072
#define DOgCharset_EBCDIC_IT                                     2072
#define DOgCharset_csEBCDICPT                                    2073
#define DOgCharset_EBCDIC_PT                                     2073
#define DOgCharset_csEBCDICES                                    2074
#define DOgCharset_EBCDIC_ES                                     2074
#define DOgCharset_csEBCDICESA                                   2075
#define DOgCharset_EBCDIC_ES_A                                   2075
#define DOgCharset_csEBCDICESS                                   2076
#define DOgCharset_EBCDIC_ES_S                                   2076
#define DOgCharset_csEBCDICUK                                    2077
#define DOgCharset_EBCDIC_UK                                     2077
#define DOgCharset_csEBCDICUS                                    2078
#define DOgCharset_EBCDIC_US                                     2078
#define DOgCharset_csUnknown8BiT                                 2079
#define DOgCharset_UNKNOWN_8BIT                                  2079
#define DOgCharset_csMnemonic                                    2080
#define DOgCharset_MNEMONIC                                      2080
#define DOgCharset_csMnem                                        2081
#define DOgCharset_MNEM                                          2081
#define DOgCharset_csVISCII                                      2082
#define DOgCharset_VISCII                                        2082
#define DOgCharset_csVIQR                                        2083
#define DOgCharset_VIQR                                          2083
#define DOgCharset_csKOI8R                                       2084
#define DOgCharset_KOI8_R                                        2084
#define DOgCharset_HZ_GB_2312                                    2085
#define DOgCharset_866                                           2086
#define DOgCharset_cp866                                         2086
#define DOgCharset_csIBM866                                      2086
#define DOgCharset_IBM866                                        2086
#define DOgCharset_cp775                                         2087
#define DOgCharset_csPC775Baltic                                 2087
#define DOgCharset_IBM775                                        2087
#define DOgCharset_KOI8_U                                        2088
#define DOgCharset_CCSID00858                                    2089
#define DOgCharset_CP00858                                       2089
#define DOgCharset_IBM00858                                      2089
#define DOgCharset_PC_Multilingual_850_euro                      2089
#define DOgCharset_CCSID00924                                    2090
#define DOgCharset_CP00924                                       2090
#define DOgCharset_ebcdic_Latin9__euro                           2090
#define DOgCharset_IBM00924                                      2090
#define DOgCharset_CCSID01140                                    2091
#define DOgCharset_CP01140                                       2091
#define DOgCharset_ebcdic_us_37_euro                             2091
#define DOgCharset_IBM01140                                      2091
#define DOgCharset_CCSID01141                                    2092
#define DOgCharset_CP01141                                       2092
#define DOgCharset_ebcdic_de_273_euro                            2092
#define DOgCharset_IBM01141                                      2092
#define DOgCharset_CCSID01142                                    2093
#define DOgCharset_CP01142                                       2093
#define DOgCharset_ebcdic_dk_277_euro                            2093
#define DOgCharset_ebcdic_no_277_euro                            2093
#define DOgCharset_IBM01142                                      2093
#define DOgCharset_CCSID01143                                    2094
#define DOgCharset_CP01143                                       2094
#define DOgCharset_ebcdic_fi_278_euro                            2094
#define DOgCharset_ebcdic_se_278_euro                            2094
#define DOgCharset_IBM01143                                      2094
#define DOgCharset_CCSID01144                                    2095
#define DOgCharset_CP01144                                       2095
#define DOgCharset_ebcdic_it_280_euro                            2095
#define DOgCharset_IBM01144                                      2095
#define DOgCharset_CCSID01145                                    2096
#define DOgCharset_CP01145                                       2096
#define DOgCharset_ebcdic_es_284_euro                            2096
#define DOgCharset_IBM01145                                      2096
#define DOgCharset_CCSID01146                                    2097
#define DOgCharset_CP01146                                       2097
#define DOgCharset_ebcdic_gb_285_euro                            2097
#define DOgCharset_IBM01146                                      2097
#define DOgCharset_CCSID01147                                    2098
#define DOgCharset_CP01147                                       2098
#define DOgCharset_ebcdic_fr_297_euro                            2098
#define DOgCharset_IBM01147                                      2098
#define DOgCharset_CCSID01148                                    2099
#define DOgCharset_CP01148                                       2099
#define DOgCharset_ebcdic_international_500_euro                 2099
#define DOgCharset_IBM01148                                      2099
#define DOgCharset_CCSID01149                                    2100
#define DOgCharset_CP01149                                       2100
#define DOgCharset_ebcdic_is_871_euro                            2100
#define DOgCharset_IBM01149                                      2100
#define DOgCharset_Big5_HKSCS                                    2101
#define DOgCharset_IBM_1047                                      2102
#define DOgCharset_IBM1047                                       2102
#define DOgCharset_CP154                                         2103
#define DOgCharset_Cyrillic_Asian                                2103
#define DOgCharset_csPTCP154                                     2103
#define DOgCharset_PT154                                         2103
#define DOgCharset_PTCP154                                       2103
#define DOgCharset_Ami_1251                                      2104
#define DOgCharset_Ami1251                                       2104
#define DOgCharset_Amiga_1251                                    2104
#define DOgCharset_Amiga1251                                     2104
#define DOgCharset_KOI7_switched                                 2105
#define DOgCharset_windows_1250                                  2250
#define DOgCharset_windows_1251                                  2251
#define DOgCharset_windows_1252                                  2252
#define DOgCharset_windows_1253                                  2253
#define DOgCharset_windows_1254                                  2254
#define DOgCharset_windows_1255                                  2255
#define DOgCharset_windows_1256                                  2256
#define DOgCharset_windows_1257                                  2257
#define DOgCharset_windows_1258                                  2258
#define DOgCharset_TIS_620                                       2259


DEFPUBLIC(int) OgCharsetToCode(pr(char *));
DEFPUBLIC(char *) OgCodeToCharset(pr(int));



#define _LOGCHSETALIVE_
#endif


