/*
 *	Generic functions for language
 * 	and Encapsulation of exceptions
 *	Copyright (c) 1998	Ogmios par Patrick Constant
 *	Dev : October 1998
 *	Version 1.0
*/
#include <loggen.h>

struct og_exception {
  int value;
  char *string;
  };


#if (DPcSystem == DPcSystemUnix)

#define EXCEPTION_ACCESS_VIOLATION -1073741819
#define EXCEPTION_DATATYPE_MISALIGNMENT -2147483646
#define EXCEPTION_BREAKPOINT -2147483645
#define EXCEPTION_SINGLE_STEP -2147483644
#define EXCEPTION_ARRAY_BOUNDS_EXCEEDED -1073741684
#define EXCEPTION_FLT_DENORMAL_OPERAND -1073741683
#define EXCEPTION_FLT_DIVIDE_BY_ZERO -1073741682
#define EXCEPTION_FLT_INEXACT_RESULT -1073741681
#define EXCEPTION_FLT_INVALID_OPERATION -1073741680
#define EXCEPTION_FLT_OVERFLOW -1073741679
#define EXCEPTION_FLT_STACK_CHECK -1073741678
#define EXCEPTION_FLT_UNDERFLOW -1073741677
#define EXCEPTION_INT_DIVIDE_BY_ZERO -1073741676
#define EXCEPTION_INT_OVERFLOW -1073741675
#define EXCEPTION_PRIV_INSTRUCTION -1073741674
#define EXCEPTION_IN_PAGE_ERROR -1073741818
#define EXCEPTION_ILLEGAL_INSTRUCTION -1073741795
#define EXCEPTION_NONCONTINUABLE_EXCEPTION -1073741787
#define EXCEPTION_STACK_OVERFLOW -1073741571
#define EXCEPTION_INVALID_DISPOSITION -1073741786
#define EXCEPTION_GUARD_PAGE -2147483647
#define EXCEPTION_INVALID_HANDLE -1073741816

#endif

struct og_exception OgException[] = {
  {EXCEPTION_ACCESS_VIOLATION,"ACCESS_VIOLATION"},
  {EXCEPTION_DATATYPE_MISALIGNMENT,"DATATYPE_MISALIGNMENT"},
  {EXCEPTION_BREAKPOINT,"BREAKPOINT"},
  {EXCEPTION_SINGLE_STEP,"SINGLE_STEP"},
  {EXCEPTION_ARRAY_BOUNDS_EXCEEDED,"ARRAY_BOUNDS_EXCEEDED"},
  {EXCEPTION_FLT_DENORMAL_OPERAND,"FLOAT_DENORMAL_OPERAND"},
  {EXCEPTION_FLT_DIVIDE_BY_ZERO,"FLOAT_DIVIDE_BY_ZERO"},
  {EXCEPTION_FLT_INEXACT_RESULT,"FLOAT_INEXACT_RESULT"},
  {EXCEPTION_FLT_INVALID_OPERATION,"FLOAT_INVALID_OPERATION"},
  {EXCEPTION_FLT_OVERFLOW,"FLOAT_OVERFLOW"},
  {EXCEPTION_FLT_STACK_CHECK,"FLOAT_STACK_CHECK"},
  {EXCEPTION_FLT_UNDERFLOW,"FLOAT_UNDERFLOW"},
  {EXCEPTION_INT_DIVIDE_BY_ZERO,"INTEGER_DIVIDE_BY_ZERO"},
  {EXCEPTION_INT_OVERFLOW,"INTEGER_OVERFLOW"},
  {EXCEPTION_PRIV_INSTRUCTION,"PRIVILEGED_INSTRUCTION"},
  {EXCEPTION_IN_PAGE_ERROR,"IN_PAGE_ERROR"},
  {EXCEPTION_ILLEGAL_INSTRUCTION,"ILLEGAL_INSTRUCTION"},
  {EXCEPTION_NONCONTINUABLE_EXCEPTION,"NONCONTINUABLE_EXCEPTION"},
  {EXCEPTION_STACK_OVERFLOW,"STACK_OVERFLOW"},
  {EXCEPTION_INVALID_DISPOSITION,"INVALID_DISPOSITION"},
  {EXCEPTION_GUARD_PAGE,"GUARD_PAGE_VIOLATION"},
  {EXCEPTION_INVALID_HANDLE,"INVALID_HANDLE"},
  {0,""}
  };


/*
 *	This function gets the language string in 2 characters
 */

PUBLIC(char *) OgExceptionToStr(int exception)
{
int i;
for (i=0; OgException[i].string[0]!=0; i++) {
  if (exception==OgException[i].value) return(OgException[i].string);
  }
return(OgException[i].string);
}
