source 'https://rubygems.org/'

gem 'activesupport'

gem 'dotenv'
gem 'minitest'
gem 'minitest-reporters'
gem 'rest-client'

gem 'rake'
gem 'parallel'

gem 'awesome_print'
gem 'term-ansicolor'
gem 'uuidtools'

# single test runner
gem 'm'

gem 'mocha'
gem 'simplecov', :require => false
gem 'redis', '~>3.3.0'
