source 'https://rubygems.org/'

gem 'bundler', '~>1.17.0'

gem 'activesupport', '~>5.2'

gem 'dotenv'
gem 'minitest'
gem 'minitest-reporters'
gem 'parallel'
gem 'redis', '~>3.3.0'
gem 'rest-client'

gem 'rake'

gem 'awesome_print'
gem 'term-ansicolor'
gem 'uuidtools'

# single test runner
gem 'm'

gem 'mocha'
gem 'simplecov', require: false
