source 'https://rubygems.org/'

gem 'activesupport'

gem 'dotenv'
gem 'minitest', '~>5.10.3'
gem 'minitest-reporters'
gem 'rest-client'

gem 'rake'
gem 'parallel'

gem 'awesome_print'
gem 'term-ansicolor'
gem 'uuidtools'

# single test runner
gem 'm'
