/*
 * Handling Cjk (Chinese Japanese Corean) punctuations
 * Copyright (c) 2009 Pertimm by Patrick Constant
 * Dev : November 2009
 * Version 1.0
*/
#include <loguni.h>



PUBLIC(int) OgUniCjkIsPunct(int c)
{
/** Japanese style punctuation **/
if (0x3000<=c && c<=0x303f) return(1);
switch (c) {
 case 0x00A7: /*	# SECTION SIGN */
 case 0x00B1: /*	# PLUS-MINUS SIGN */
 case 0x00B7: /*	# MIDDLE DOT */
 case 0x00D7: /*	# MULTIPLICATION SIGN */
 case 0x00F7: /*	# DIVISION SIGN */
 case 0x2013: /*	# EN DASH */
 case 0x2014: /*	# EM DASH */
 case 0x2018: /*	# LEFT SINGLE QUOTATION MARK */
 case 0x2019: /*	# RIGHT SINGLE QUOTATION MARK */
 case 0x201C: /*	# LEFT DOUBLE QUOTATION MARK */
 case 0x201D: /*	# RIGHT DOUBLE QUOTATION MARK */
 case 0x2022: /*	# BULLET */
 case 0x2025: /*	# TWO DOT LEADER */
 case 0x2026: /*	# HORIZONTAL ELLIPSIS */
 case 0x2032: /*	# PRIME */
 case 0x2035: /*	# REVERSED PRIME */
 case 0x203B: /*	# REFERENCE MARK */
 case 0x203E: /*	# OVERLINE */
 case 0x2105: /*	# CARE OF */
 case 0x2190: /*	# LEFTWARDS ARROW */
 case 0x2191: /*	# UPWARDS ARROW */
 case 0x2192: /*	# RIGHTWARDS ARROW */
 case 0x2193: /*	# DOWNWARDS ARROW */
 case 0x2196: /*	# NORTH WEST ARROW */
 case 0x2197: /*	# NORTH EAST ARROW */
 case 0x2198: /*	# SOUTH EAST ARROW */
 case 0x2199: /*	# SOUTH WEST ARROW */
 case 0x221A: /*	# SQUARE ROOT */
 case 0x221E: /*	# INFINITY */
 case 0x221F: /*	# RIGHT ANGLE */
 case 0x2220: /*	# ANGLE */
 case 0x2223: /*	# DIVIDES */
 case 0x2225: /*	# PARALLEL TO */
 case 0x2229: /*	# INTERSECTION */
 case 0x222A: /*	# UNION */
 case 0x222B: /*	# INTEGRAL */
 case 0x222E: /*	# CONTOUR INTEGRAL */
 case 0x2234: /*	# THEREFORE */
 case 0x2235: /*	# BECAUSE */
 case 0x223C: /*	# TILDE OPERATOR */
 case 0x2252: /*	# APPROXIMATELY EQUAL TO OR THE IMAGE OF */
 case 0x2260: /*	# NOT EQUAL TO */
 case 0x2261: /*	# IDENTICAL TO */
 case 0x2266: /*	# LESS THAN OVER EQUAL TO */
 case 0x2267: /*	# GREATER THAN OVER EQUAL TO */
 case 0x22A5: /*	# UP TACK */
 case 0x22BF: /*	# RIGHT TRIANGLE */
 case 0x25A0: /*	# BLACK SQUARE */
 case 0x25A1: /*	# WHITE SQUARE */
 case 0x25B2: /*	# BLACK UP-POINTING TRIANGLE */
 case 0x25B3: /*	# WHITE UP-POINTING TRIANGLE */
 case 0x25BC: /*	# BLACK DOWN-POINTING TRIANGLE */
 case 0x25BD: /*	# WHITE DOWN-POINTING TRIANGLE */
 case 0x25C6: /*	# BLACK DIAMOND */
 case 0x25C7: /*	# WHITE DIAMOND */
 case 0x25CB: /*	# WHITE CIRCLE */
 case 0x25CE: /*	# BULLSEYE */
 case 0x25CF: /*	# BLACK CIRCLE */
 case 0x2605: /*	# BLACK STAR */
 case 0x2606: /*	# WHITE STAR */
 case 0x2609: /*	# SUN */
 case 0x2640: /*	# FEMALE SIGN */
 case 0x2641: /*	# EARTH */
 case 0x2642: /*	# MALE SIGN */
 case 0x32A3: /*	# CIRCLED IDEOGRAPH CORRECT */
 case 0x33D1: /*	# SQUARE LN */
 case 0x33D2: /*	# SQUARE LOG */
 case 0xFE30: /*	# PRESENTATION FORM FOR VERTICAL TWO DOT LEADER */
 case 0xFE31: /*	# PRESENTATION FORM FOR VERTICAL EM DASH */
 case 0xFE33: /*	# PRESENTATION FORM FOR VERTICAL LOW LINE */
 case 0xFE34: /*	# PRESENTATION FORM FOR VERTICAL WAVY LOW LINE */
 case 0xFE35: /*	# PRESENTATION FORM FOR VERTICAL LEFT PARENTHESIS */
 case 0xFE36: /*	# PRESENTATION FORM FOR VERTICAL RIGHT PARENTHESIS */
 case 0xFE37: /*	# PRESENTATION FORM FOR VERTICAL LEFT CURLY BRACKET */
 case 0xFE38: /*	# PRESENTATION FORM FOR VERTICAL RIGHT CURLY BRACKET */
 case 0xFE39: /*	# PRESENTATION FORM FOR VERTICAL LEFT TORTOISE SHELL BRACKET */
 case 0xFE3A: /*	# PRESENTATION FORM FOR VERTICAL RIGHT TORTOISE SHELL BRACKET */
 case 0xFE3B: /*	# PRESENTATION FORM FOR VERTICAL LEFT BLACK LENTICULAR BRACKET */
 case 0xFE3C: /*	# PRESENTATION FORM FOR VERTICAL RIGHT BLACK LENTICULAR BRACKET */
 case 0xFE3D: /*	# PRESENTATION FORM FOR VERTICAL LEFT DOUBLE ANGLE BRACKET */
 case 0xFE3E: /*	# PRESENTATION FORM FOR VERTICAL RIGHT DOUBLE ANGLE BRACKET */
 case 0xFE3F: /*	# PRESENTATION FORM FOR VERTICAL LEFT ANGLE BRACKET */
 case 0xFE40: /*	# PRESENTATION FORM FOR VERTICAL RIGHT ANGLE BRACKET */
 case 0xFE41: /*	# PRESENTATION FORM FOR VERTICAL LEFT CORNER BRACKET */
 case 0xFE42: /*	# PRESENTATION FORM FOR VERTICAL RIGHT CORNER BRACKET */
 case 0xFE43: /*	# PRESENTATION FORM FOR VERTICAL LEFT WHITE CORNER BRACKET */
 case 0xFE44: /*	# PRESENTATION FORM FOR VERTICAL RIGHT WHITE CORNER BRACKET */
 case 0xFE49: /*	# DASHED OVERLINE */
 case 0xFE4A: /*	# CENTRELINE OVERLINE */
 case 0xFE4B: /*	# WAVY OVERLINE */
 case 0xFE4C: /*	# DOUBLE WAVY OVERLINE */
 case 0xFE4D: /*	# DASHED LOW LINE */
 case 0xFE4E: /*	# CENTRELINE LOW LINE */
 case 0xFE4F: /*	# WAVY LOW LINE */
 case 0xFE50: /*	# SMALL COMMA */
 case 0xFE52: /*	# SMALL FULL STOP */
 case 0xFE54: /*	# SMALL SEMICOLON */
 case 0xFE55: /*	# SMALL COLON */
 case 0xFE56: /*	# SMALL QUESTION MARK */
 case 0xFE57: /*	# SMALL EXCLAMATION MARK */
 case 0xFE59: /*	# SMALL LEFT PARENTHESIS */
 case 0xFE5A: /*	# SMALL RIGHT PARENTHESIS */
 case 0xFE5B: /*	# SMALL LEFT CURLY BRACKET */
 case 0xFE5C: /*	# SMALL RIGHT CURLY BRACKET */
 case 0xFE5D: /*	# SMALL LEFT TORTOISE SHELL BRACKET */
 case 0xFE5E: /*	# SMALL RIGHT TORTOISE SHELL BRACKET */
 case 0xFE5F: /*	# SMALL NUMBER SIGN */
 case 0xFE60: /*	# SMALL AMPERSAND */
 case 0xFE61: /*	# SMALL ASTERISK */
 case 0xFE62: /*	# SMALL PLUS SIGN */
 case 0xFE63: /*	# SMALL HYPHEN-MINUS */
 case 0xFE64: /*	# SMALL LESS-THAN SIGN */
 case 0xFE65: /*	# SMALL GREATER-THAN SIGN */
 case 0xFE66: /*	# SMALL EQUALS SIGN */
 case 0xFF01: /*	# FULLWIDTH EXCLAMATION MARK */
 case 0xFF03: /*	# FULLWIDTH NUMBER SIGN */
 case 0xFF06: /*	# FULLWIDTH AMPERSAND */
 case 0xFF08: /*	# FULLWIDTH LEFT PARENTHESIS */
 case 0xFF09: /*	# FULLWIDTH RIGHT PARENTHESIS */
 case 0xFF0A: /*	# FULLWIDTH ASTERISK */
 case 0xFF0B: /*	# FULLWIDTH PLUS SIGN */
 case 0xFF0C: /*	# FULLWIDTH COMMA */
 case 0xFF0D: /*	# FULLWIDTH HYPHEN-MINUS */
 case 0xFF0E: /*	# FULLWIDTH FULL STOP */
 case 0xFF1A: /*	# FULLWIDTH COLON */
 case 0xFF1B: /*	# FULLWIDTH SEMICOLON */
 case 0xFF1C: /*	# FULLWIDTH LESS-THAN SIGN */
 case 0xFF1D: /*	# FULLWIDTH EQUALS SIGN */
 case 0xFF1E: /*	# FULLWIDTH GREATER-THAN SIGN */
 case 0xFF1F: /*	# FULLWIDTH QUESTION MARK */
 case 0xFF3F: /*	# FULLWIDTH LOW LINE */
 case 0xFF5B: /*	# FULLWIDTH LEFT CURLY BRACKET */
 case 0xFF5C: /*	# FULLWIDTH VERTICAL BAR */
 case 0xFF5D: /*	# FULLWIDTH RIGHT CURLY BRACKET */
 case 0xFF64: /*	# HALFWIDTH IDEOGRAPHIC COMMA */
   return(1);
 }
return(0);
}



