source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.1.4'

# Use postgresql as the database for Active Record
gem 'pg', '~> 0.18'

# Use Puma as the app server
gem 'puma', '~> 3.7'

# Environment variables at boostrap time
gem 'dotenv-rails', '~> 2.1', '>= 2.1.1'

# Use Devise as authentication solution
gem 'devise', '~> 4.3.0'
gem 'devise_invitable', '~> 1.7.2'
gem 'friendly_id', '~> 5.1.0'

# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'

# Use Redis adapter to run Action Cable in production
gem 'redis', '~> 3.0'

# Use Sidekiq to manage background jobs
gem 'sidekiq'

# Use Foreman to run app and dependencies
gem 'foreman'

gem 'awesome_print'
gem 'kaminari'
gem 'rainbow'

# Upload (shrine & dependencies)
gem 'shrine'
gem 'image_processing'
gem 'mini_magick', '>= 4.3.5'

# Graph
gem 'rgl'

# Mailing
gem 'postmark-rails'
gem 'inky-rb', require: 'inky'
gem 'premailer-rails'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem 'webpacker'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
gem 'listen', '>= 3.0.5', '< 3.2'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'capybara', '~> 2.13'
  gem 'selenium-webdriver'
end

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'mocha'
  gem 'shrine-memory'
  gem 'simplecov', require: false
end

# gem 'rubocop', require: false
