source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '~> 2.6.4'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.0'

# Use postgresql as the database for Active Record
gem 'pg', '~> 0.18'

# Use Puma as the app server
gem 'puma', '~> 3.11'

gem 'oj'

# Use last version of CSV gem
gem 'csv'

# Environment variables at boostrap time
gem 'dotenv-rails', '~> 2.7'

# Use Devise as authentication solution
gem 'devise', '~> 4.7.1'
gem 'devise_invitable', '~> 2.0.1'
gem 'friendly_id', '~> 5.2.5'

# Allow admin to switch user
gem 'pretender'

# Keep emails from escaping into the wild during development
gem "mail_safe", group: [:development]

# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.7'

# Use Redis adapter to run Action Cable in production
gem 'redis', '~> 4.0'
gem 'hiredis'

gem 'local_time'

# Use Sidekiq to manage background jobs
gem 'sidekiq'

# Use ElasticSearch for stats
gem 'elasticsearch', '~> 7.3'

# Use Foreman to run app and dependencies
gem 'foreman'

gem 'awesome_print'
gem 'kaminari'
gem 'rainbow'

# Upload (shrine & dependencies)
gem 'shrine'
gem 'image_processing'
gem 'mini_magick', '>= 4.3.5'

# Markdown
gem 'html-pipeline'
gem "commonmarker", "~> 0.16", require: false
gem "sanitize", "~> 4.6", require: false
gem "rinku", "~> 1.7", require: false

# Graph
gem 'rgl'

# Mailing
gem 'postmark-rails'
gem 'inky-rb', require: 'inky'
gem 'premailer-rails'

# Duplicate model
gem 'clowne'

# Emoji regex
gem 'unicode-emoji'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 5'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem 'webpacker', '~> 4.0'

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 5.0'

# Bulk inserts in active record
gem 'activerecord-import'

# YAJL JSON parsing and generation library
gem 'yajl-ruby', require: 'yajl'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.2', require: false

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'mocha'
  gem 'shrine-memory'
  gem 'simplecov', require: false
end

# Skylight: profiler for Ruby on Rails applications.
group :production do
  gem "skylight"
end

# Used by PingPongBot Sinatra App
gem 'sinatra', require: 'sinatra/base'
gem 'sinatra-contrib', require: false
gem 'rest-client'
