redis:    docker kill viky-redis-dev; docker run -p "6379:6379" --rm --name viky-redis-dev --init redis:3.2-alpine
workers:  bundle exec sidekiq -C config/sidekiq.yml -L ./log/sidekiq.log
webpack:  ./bin/webpack-dev-server
web:      bundle exec rails s -p 3000 -b 0.0.0.0
nls:       ./bin/foreman_nls.sh $MY_CURRENT_GIT_BRANCH
doc:      bundle exec rails doc:server
stats:    docker kill viky-stats01-dev; docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" --rm --mount 'type=volume,src=vikyapp_stats01,dst=/usr/share/elasticsearch/data' --name viky-stats01-dev docker.elastic.co/elasticsearch/elasticsearch:6.3.0
