sidekiq_redis:  redis-server --port 7372
workers:        bundle exec sidekiq -C config/sidekiq.yml -L ./log/sidekiq.log
webpack:        ./bin/webpack-dev-server
web:            bundle exec rails s -p 3000
nlp_server:     docker pull docker-registry.pertimm.net/voqal.ai/platform/nlp:latest ; docker run --rm --name foreman_nlp_server --sig-proxy=true --volume "$(pwd)/import:/nls/import" -p "9345:9345" docker-registry.pertimm.net/voqal.ai/platform/nlp
doc:             bundle exec rails doc:server
